[package]
authors     = ["Braden Steffaniak"]
categories  = ["multimedia", "network-programming"]
description = "MoosicBox Qobuz package"
edition     = "2021"
keywords    = ["audio", "qobuz"]
license     = "MPL-2.0"
name        = "moosicbox_qobuz"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBoxServer"
version     = "0.1.0"

[dependencies]
moosicbox_assert = { path = "../assert", default-features = false }
moosicbox_core = { path = "../core", default-features = false }
moosicbox_database = { path = "../database", default-features = false, features = [
    "sqlite-sqlx",
] }
moosicbox_files = { path = "../files", default-features = false }
moosicbox_json_utils = { path = "../json_utils", default-features = false, features = [
    "database",
    "serde_json",
] }
moosicbox_menu = { path = "../menu", default-features = false }
moosicbox_music_api = { path = "../music_api", default-features = false }
moosicbox_paging = { path = "../paging", default-features = false }
moosicbox_search = { path = "../search", default-features = false }

# API Dependencies
actix-web = { workspace = true, optional = true }
utoipa    = { workspace = true, optional = true }

# DB Dependencies
rusqlite = { workspace = true, optional = true }

async-recursion = { workspace = true }
async-trait     = { workspace = true }
base64          = { workspace = true }
log             = { workspace = true }
md5             = { workspace = true }
once_cell       = { workspace = true }
open            = { workspace = true }
regex           = { workspace = true }
reqwest         = { workspace = true, features = ["json"] }
serde           = { workspace = true, features = ["derive"] }
serde_json      = { workspace = true }
strum           = { workspace = true }
strum_macros    = { workspace = true }
thiserror       = { workspace = true }
tokio           = { workspace = true, features = ["macros", "tracing"] }
tokio-util      = { workspace = true }
url             = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }

[features]
default = ["api", "db", "openapi"]

fail-on-warnings = []

api     = ["dep:actix-web"]
db      = ["dep:rusqlite", "moosicbox_music_api/db"]
openapi = ["dep:utoipa"]
