[package]
authors = ["Braden Steffaniak"]
edition = "2021"
name    = "moosicbox_qobuz"
version = "0.1.0"

[dependencies]
moosicbox_core       = { path = "../core", default-features = false }
moosicbox_json_utils = { path = "../json_utils", default-features = false, features = [
    "serde_json",
] }

# API Dependencies
actix-web = { workspace = true, optional = true }

# DB Dependencies
rusqlite = { workspace = true, optional = true }

async-recursion = { workspace = true }
base64          = { workspace = true }
log             = { workspace = true }
md5             = { workspace = true }
once_cell       = { workspace = true }
open            = { workspace = true }
regex           = { workspace = true }
reqwest         = { workspace = true, features = ["json"] }
serde           = { workspace = true, features = ["derive"] }
serde_json      = { workspace = true }
strum           = { workspace = true }
strum_macros    = { workspace = true }
thiserror       = { workspace = true }
url             = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }

[features]
default = ["api", "db"]

fail-on-warnings = []

api = ["dep:actix-web"]
db  = ["dep:rusqlite"]
