[package]
authors = ["Braden Steffaniak"]
edition = "2021"
name    = "moosicbox_menu"
version = "0.1.0"

[dependencies]
moosicbox_core = { path = "../core", default-features = false }

actix-cors  = { workspace = true }
actix-files = { workspace = true }
actix-web   = { workspace = true }
awc         = { workspace = true }
log         = { workspace = true }
serde       = { workspace = true, features = ["derive"] }
serde_json  = { workspace = true }
thiserror   = { workspace = true }

[features]
fail-on-warnings = []
