[package]
authors     = ["Braden Steffaniak"]
categories  = ["development-tools"]
description = "MoosicBox menu package"
edition     = "2021"
keywords    = ["album", "artist", "menu", "playlist", "track"]
license     = "MPL-2.0"
name        = "moosicbox_menu"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBoxServer"
version     = "0.1.0"

[dependencies]
moosicbox_assert = { path = "../assert", default-features = false }
moosicbox_core = { path = "../core", default-features = false }
moosicbox_database = { path = "../database", default-features = false, features = [
    "sqlite-sqlx",
] }
moosicbox_library = { path = "../library", default-features = false }
moosicbox_music_api = { path = "../music_api", features = ["db"] }
moosicbox_paging = { path = "../paging", default-features = false }
moosicbox_scan = { path = "../scan", default-features = false }
moosicbox_search = { path = "../search", default-features = false }
moosicbox_session = { path = "../session", default-features = false }

# API Dependencies
utoipa = { workspace = true, optional = true }

actix-web = { workspace = true }
log       = { workspace = true }
serde     = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
tokio     = { workspace = true }

[features]
default = ["api", "local", "openapi"]

fail-on-warnings = []

local = ["moosicbox_scan/local"]

api     = ["moosicbox_library/api", "moosicbox_music_api/api"]
openapi = ["dep:utoipa", "moosicbox_core/openapi", "moosicbox_library/openapi"]
