[package]
name = "moosicbox_menu"
version = "0.1.0"
authors = ["Braden Steffaniak"]
edition = "2021"

[dependencies]
actix-cors = "0.6.4"
actix-files = "0.6.2"
actix-web = "4.4.0"
awc = "3.0.0-beta.9"
lambda-web = { version = "0.2.1", features=["actix4"] }
lambda_runtime = "0.8.2"
log = { workspace = true }
moosicbox_core = { path = "../core" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }

[features]
fail-on-warnings = []
