[package]
authors     = ["Braden Steffaniak"]
categories  = ["development-tools"]
description = "MoosicBox menu package"
edition     = "2021"
keywords    = ["album", "artist", "menu", "playlist", "track"]
license     = "MPL-2.0"
name        = "moosicbox_menu"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBoxServer"
version     = "0.1.0"

[dependencies]
moosicbox_assert = { workspace = true, default-features = false }
moosicbox_core = { workspace = true, default-features = false }
moosicbox_database = { workspace = true, default-features = false, features = [
    "rusqlite",
] }
moosicbox_music_api = { workspace = true, features = ["db"] }
moosicbox_paging = { workspace = true, default-features = false }
moosicbox_qobuz = { workspace = true, default-features = false }
moosicbox_scan = { workspace = true, default-features = false }
moosicbox_search = { workspace = true, default-features = false }
moosicbox_tidal = { workspace = true, default-features = false }

actix-cors      = { workspace = true }
actix-files     = { workspace = true }
actix-web       = { workspace = true }
async-recursion = { workspace = true }
awc             = { workspace = true }
futures         = { workspace = true }
log             = { workspace = true }
serde           = { workspace = true, features = ["derive"] }
serde_json      = { workspace = true }
thiserror       = { workspace = true }
tokio           = { workspace = true }

[features]
default = ["local", "qobuz", "tidal"]

fail-on-warnings = []

local = ["moosicbox_scan/local"]
qobuz = ["moosicbox_scan/qobuz"]
tidal = ["moosicbox_scan/tidal"]
