[package]
authors     = ["Braden Steffaniak"]
categories  = ["gui", "web-programming"]
description = "GigaChad color package"
edition     = "2021"
keywords    = ["color", "gui", "web"]
license     = "MPL-2.0"
name        = "gigachad_color"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBox"
version     = "0.1.0"

[dependencies]
moosicbox_assert = { version = "0.1.0", path = "../../assert", default-features = false }

color-hex = { workspace = true }
egui      = { workspace = true, optional = true }
log       = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
test-log          = { workspace = true }

[features]
default = ["egui"]

egui = ["dep:egui"]

fail-on-warnings = []
