[package]
authors     = ["Braden Steffaniak"]
categories  = ["multimedia", "network-programming"]
description = "MoosicBox downloader package"
edition     = "2021"
keywords    = ["audio", "download", "downloader", "multimedia"]
license     = "MPL-2.0"
name        = "moosicbox_downloader"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBoxServer"
version     = "0.1.0"

[dependencies]
moosicbox_assert = { workspace = true, default-features = false }
moosicbox_config = { workspace = true, default-features = false }
moosicbox_core = { workspace = true, default-features = false }
moosicbox_database = { workspace = true, default-features = false, features = [
    "rusqlite",
] }
moosicbox_files = { workspace = true, default-features = false, features = [
    "files",
] }
moosicbox_json_utils = { workspace = true, default-features = false, features = [
    "rusqlite",
    "serde_json",
] }
moosicbox_paging = { workspace = true, default-features = false }

# API Dependencies
actix-web = { workspace = true, optional = true }

async-recursion = { workspace = true }
async-trait     = { workspace = true }
atomic_float    = { workspace = true }
audiotags       = { workspace = true }
futures         = { workspace = true }
hyper           = { version = "1.3.1" }
id3             = { workspace = true }
lazy_static     = { workspace = true }
lofty           = { workspace = true }
log             = { workspace = true }
mp3-duration    = { workspace = true }
once_cell       = { workspace = true }
reqwest         = { workspace = true, features = ["json"] }
rusqlite        = { workspace = true }
serde           = { workspace = true, features = ["derive"] }
serde_json      = { workspace = true }
strum           = { workspace = true }
strum_macros    = { workspace = true }
thiserror       = { workspace = true }
tokio           = { workspace = true }
tokio-util      = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
serial_test       = { workspace = true }
static_init       = { workspace = true }
test-log          = { workspace = true }
tokio             = { workspace = true, features = ["macros", "rt"] }

[features]
default = ["aac", "api", "flac", "mp3", "opus"]

fail-on-warnings = []

api = ["dep:actix-web"]

aac  = ["moosicbox_core/aac", "moosicbox_files/aac"]
flac = ["moosicbox_core/flac", "moosicbox_files/flac"]
mp3  = ["moosicbox_core/mp3", "moosicbox_files/mp3"]
opus = ["moosicbox_core/opus", "moosicbox_files/opus"]
