[package]
authors     = ["Braden Steffaniak"]
categories  = ["multimedia", "network-programming"]
description = "MoosicBox downloader package"
edition     = "2021"
keywords    = ["audio", "download", "downloader", "multimedia"]
license     = "MPL-2.0"
name        = "moosicbox_downloader"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBoxServer"
version     = "0.1.0"

[package.metadata.cargo-machete]
ignored = ["strum"]

[dependencies]
moosicbox_assert = { path = "../assert", default-features = false }
moosicbox_config = { path = "../config", default-features = false }
moosicbox_core = { path = "../core", default-features = false }
moosicbox_database = { path = "../database", default-features = false }
moosicbox_files = { path = "../files", default-features = false, features = [
    "files",
] }
moosicbox_json_utils = { path = "../json_utils", default-features = false, features = [
    "serde_json",
] }
moosicbox_music_api = { path = "../music_api", default-features = false }
moosicbox_paging = { path = "../paging", default-features = false }
moosicbox_scan = { path = "../scan", default-features = false, features = [
    "local",
] }
moosicbox_task = { path = "../task", default-features = false }

# API Dependencies
actix-web = { workspace = true, optional = true }
utoipa    = { workspace = true, optional = true }

async-recursion = { workspace = true }
async-trait     = { workspace = true }
atomic_float    = { workspace = true }
audiotags       = { workspace = true }
futures         = { workspace = true }
hyper           = { version = "1.4.1" }
id3             = { workspace = true }
lazy_static     = { workspace = true }
log             = { workspace = true }
regex           = { workspace = true }
serde           = { workspace = true, features = ["derive"] }
serde_json      = { workspace = true }
strum           = { workspace = true }
strum_macros    = { workspace = true }
thiserror       = { workspace = true }
tokio           = { workspace = true }
tokio-util      = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
test-log          = { workspace = true }
tokio             = { workspace = true, features = ["macros", "rt", "tracing"] }

[features]
default = ["aac", "api", "flac", "mp3", "openapi", "opus"]

fail-on-warnings = []

api = ["dep:actix-web", "moosicbox_database/api", "moosicbox_music_api/api"]
openapi = [
    "dep:utoipa",
    "moosicbox_core/openapi",
    "moosicbox_music_api/openapi",
    "moosicbox_paging/openapi",
]

aac  = ["moosicbox_core/aac", "moosicbox_files/aac"]
flac = ["moosicbox_core/flac", "moosicbox_files/flac"]
mp3  = ["moosicbox_core/mp3", "moosicbox_files/mp3"]
opus = ["moosicbox_core/opus", "moosicbox_files/opus"]
