[package]
authors = ["Braden Steffaniak"]
edition = "2021"
name    = "moosicbox_tunnel"
version = "0.1.0"

[dependencies]
base64            = { workspace = true, optional = true }
bytes             = { workspace = true }
crossbeam-channel = { workspace = true }
futures-channel   = { workspace = true, optional = true }
futures-util      = { workspace = true }
lazy_static       = { workspace = true, optional = true }
log               = { workspace = true }
moosicbox_core    = { path = "../core", optional = true }
moosicbox_files   = { path = "../files", optional = true }
once_cell         = { workspace = true, optional = true }
serde             = { workspace = true, features = ["derive"] }
serde-aux         = { workspace = true, optional = true }
serde_json        = { workspace = true, optional = true }
strum             = { workspace = true }
strum_macros      = { workspace = true }
thiserror         = { workspace = true, optional = true }
tokio             = { workspace = true }
tokio-tungstenite = { workspace = true, optional = true }

[features]
default = ["sender", "base64"]

fail-on-warnings = []

base64 = ["dep:base64"]
sender = [
    "dep:futures-channel",
    "dep:lazy_static",
    "dep:moosicbox_core",
    "dep:moosicbox_files",
    "dep:once_cell",
    "dep:serde-aux",
    "dep:serde_json",
    "dep:thiserror",
    "dep:tokio-tungstenite",
]
