[package]
authors     = ["Braden Steffaniak"]
categories  = ["network-programming"]
description = "MoosicBox tunnel package"
edition     = "2021"
keywords    = ["api", "tunnel", "websocket"]
license     = "MPL-2.0"
name        = "moosicbox_tunnel"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBoxServer"
version     = "0.1.0"

[dependencies]
moosicbox_assert = { path = "../assert", default-features = false }

# Base64 dependencies
base64 = { workspace = true, optional = true }

bytes             = { workspace = true }
futures-util      = { workspace = true }
log               = { workspace = true }
rand              = { workspace = true }
regex             = { workspace = true }
serde             = { workspace = true, features = ["derive"] }
serde_json        = { workspace = true }
strum             = { workspace = true }
strum_macros      = { workspace = true }
thiserror         = { workspace = true }
tokio             = { workspace = true, features = ["rt", "tracing"]}
tokio-util        = { workspace = true }

[features]
default = ["base64"]

fail-on-warnings = []

base64 = ["dep:base64"]
