[package]
authors = ["Braden Steffaniak"]
edition = "2021"
name    = "moosicbox_tunnel"
version = "0.1.0"

[dependencies]
moosicbox_auth = { path = "../auth", optional = true }
moosicbox_core = { path = "../core", optional = true, default-features = false }
moosicbox_env_utils = { path = "../env_utils", optional = true }
moosicbox_files = { path = "../files", default-features = false, optional = true }
moosicbox_image = { path = "../image", default-features = false, features = [
    "image",
], optional = true }
moosicbox_stream_utils = { path = "../stream_utils", optional = true }
moosicbox_symphonia_player = { path = "../../players/symphonia_player", default-features = false, optional = true }
moosicbox_ws = { path = "../ws", optional = true }

base64            = { workspace = true, optional = true }
bytes             = { workspace = true }
crossbeam-channel = { workspace = true }
futures-channel   = { workspace = true, optional = true }
futures-util      = { workspace = true }
lazy_static       = { workspace = true, optional = true }
log               = { workspace = true }
once_cell         = { workspace = true, optional = true }
rand              = { workspace = true }
regex             = { workspace = true }
reqwest           = { workspace = true, features = ["json"], optional = true }
serde             = { workspace = true, features = ["derive"] }
serde-aux         = { workspace = true, optional = true }
serde_json        = { workspace = true }
strum             = { workspace = true }
strum_macros      = { workspace = true }
symphonia         = { workspace = true }
thiserror         = { workspace = true }
tokio             = { workspace = true }
tokio-tungstenite = { workspace = true, optional = true }
tokio-util        = { workspace = true }

[features]
default = ["sender", "base64", "aac", "flac", "mp3", "opus"]

fail-on-warnings = []

base64 = ["dep:base64"]
sender = [
    "dep:futures-channel",
    "dep:lazy_static",
    "dep:moosicbox_auth",
    "dep:moosicbox_core",
    "dep:moosicbox_env_utils",
    "dep:moosicbox_files",
    "dep:moosicbox_image",
    "dep:moosicbox_stream_utils",
    "dep:moosicbox_symphonia_player",
    "dep:moosicbox_ws",
    "dep:once_cell",
    "dep:reqwest",
    "dep:serde-aux",
    "dep:tokio-tungstenite",
]

aac = [
    "moosicbox_symphonia_player/aac",
    "moosicbox_files/aac",
    "moosicbox_core/aac",
]
flac = ["moosicbox_core/flac"]
mp3 = [
    "moosicbox_symphonia_player/mp3",
    "moosicbox_files/mp3",
    "moosicbox_core/mp3",
]
opus = [
    "moosicbox_symphonia_player/opus",
    "moosicbox_files/opus",
    "moosicbox_core/opus",
]
