[package]
authors     = ["Braden Steffaniak"]
categories  = ["gui", "web-programming"]
description = "MoosicBox Marketing Website UI"
edition     = "2021"
keywords    = ["dom", "gui", "transformer", "web"]
license     = "MPL-2.0"
name        = "moosicbox_marketing_site_ui"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBox"
version     = "0.1.0"

[dependencies]
gigachad_transformer_models = { version = "0.1.0", path = "../../gigachad/transformer/models", default-features = false, features = [
    "serde",
] }
moosicbox_app_native_image = { version = "0.1.0", path = "../../app/native/image", default-features = false }

log  = { workspace = true }
maud = { workspace = true }

[features]
default = []

fail-on-warnings = []

bundled_images = []
