[package]
authors     = ["Braden Steffaniak"]
categories  = ["development-tools", "gui", "web-programming"]
description = "GigaChad Transformer package"
edition     = "2021"
keywords    = ["dom", "gigachad", "gui", "transformer", "web"]
license     = "MPL-2.0"
name        = "gigachad_transformer"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBox"
version     = "0.1.0"

[dependencies]
gigachad_color = { path = "../color", default-features = false }
moosicbox_assert = { version = "0.1.0", path = "../../assert", default-features = false }
moosicbox_logging = { version = "0.1.0", path = "../../logging", default-features = false, features = [
    "macros",
] }

html-escape = { workspace = true, optional = true }
itertools   = { workspace = true, optional = true }
log         = { workspace = true }
serde_json  = { workspace = true }
thiserror   = { workspace = true }
tl          = { workspace = true, optional = true }
xml         = { workspace = true, optional = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
test-log          = { workspace = true }

[features]
default = ["calc", "format", "html", "id"]

fail-on-warnings = []

calc = ["dep:itertools"]

html = ["dep:html-escape", "dep:tl"]
simd = ["tl?/simd"]

format = ["dep:xml"]

id = []
