apiVersion: v1
kind: Service
metadata:
    name: moosicbox-tunnel-service
    labels:
        run: moosicbox-tunnel-service
spec:
    ports:
        - port: 8004
          targetPort: 8004
          protocol: TCP
    selector:
        run: moosicbox-tunnel-service
