apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: moosicbox-tunnel-server-issuer
spec:
    acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        # server: https://acme-staging-v02.api.letsencrypt.org/directory
        email: BradenSteffaniak@gmail.com
        privateKeySecretRef:
            name: moosicbox-tunnel-server-issuer
        solvers:
            - selector: {}
              http01:
                  ingress:
                      class: moosicbox-tunnel-server-ingress
