[workspace]
members = [
    "packages/aconverter",
    "packages/auth",
    "packages/config",
    "packages/converter",
    "packages/core",
    "packages/database",
    "packages/downloader",
    "packages/env_utils",
    "packages/files",
    "packages/image",
    "packages/json_utils",
    "packages/menu",
    "packages/moosicbox",
    "packages/music_api",
    "packages/paging",
    "packages/player",
    "packages/qobuz",
    "packages/scan",
    "packages/search",
    "packages/server",
    "packages/stream_utils",
    "packages/symphonia_player",
    "packages/tidal",
    "packages/tunnel",
    "packages/tunnel_sender",
    "packages/tunnel_server",
    "packages/upnp",
    "packages/ws",
]

resolver = "2"

[profile.release]
codegen-units = 1
lto           = false
opt-level     = 3
strip         = "symbols"

[profile.debug-release]
debug    = true
inherits = "release"
strip    = "none"

[profile.release-lto]
inherits = "release"
lto      = "fat"

[profile.release-lto-no-panic]
inherits = "release-lto"
panic    = "abort"

[workspace.package]
edition = "2021"

[workspace.dependencies]
actix = "0.13.3"
actix-cors = "0.7.0"
actix-files = "0.6.5"
actix-rt = "2.9.0"
actix-web = "4.6.0"
actix-ws = "0.2.5"
arrayvec = "0.7.4"
async-once-cell = "0.5.3"
async-recursion = "1.1.1"
async-trait = "0.1.80"
atomic_float = "1.0.0"
audiopus = "0.2.0"
audiotags = { git = "https://github.com/BSteffaniak/audiotags.git", branch = "master-shallow" }
awc = "3.5.0"
aws-config = "1.4.0"
aws-sdk-apigatewaymanagement = "1.25.0"
aws-sdk-ssm = "1.28.0"
base64 = "0.22.1"
bytes = "1.6.0"
chrono = { version = "0.4.38", default-features = false, features = [
    "clock",
    "serde",
] }
clap = { version = "4.5.4", features = ["derive"] }
cpal = "0.15.3"
crossbeam-channel = "0.5.13"
debounce = "0.2.2"
derive_more = "0.99.17"
dotenv = "0.15"
enum-as-inner = "0.6.0"
env_logger = "0.11"
fdk-aac = "0.6.0"
flacenc = "0.4.0"
flume = "0.11.0"
free_log_client = { git = "https://github.com/BSteffaniak/FreeLog.git" }
futures = "0.3"
futures-channel = "0.3.30"
futures-core = "0.3.30"
futures-util = { version = "0.3.30", default-features = false, features = [
    "std",
] }
hex = "0.4.3"
home = "0.5.9"
id3 = "1.13.1"
image = "0.25.1"
io-streams = "0.16.1"
itertools = "0.12.1"
kanal = "0.1.0-pre8"
lazy_static = "1.4.0"
libpulse-binding = "2.28.1"
libpulse-simple-binding = "2.28.1"
libvips = { git = "https://github.com/BSteffaniak/libvips-rust-bindings.git", branch = "support-windows-shallow" }
lofty = { git = "https://github.com/BSteffaniak/lofty-rs.git", branch = "master-shallow" }
log = { version = "0.4", features = ["release_max_level_trace"] }
md5 = "0.7.0"
mp3-duration = "0.1.10"
mp3lame-encoder = "0.1.5"
mysql = { version = "25.0.1", features = [
    "default-rustls",
    "rustls-tls",
], default-features = false }
mysql_common = { version = "0.32.3", default-features = false }
native-tls = "0.2.11"
ogg = "0.9.1"
once_cell = { version = "1.19.0" }
open = "5.1.3"
openssl = { version = "0.10.64", features = ["v110"] }
opus = "0.3.0"
pin-project = "1.1.5"
pin-utils = "0.1.0"
postgres-native-tls = "0.5.0"
postgres-openssl = "0.5.0"
postgres-protocol = "0.6.6"
pretty_assertions = "1.4.0"
pretty_env_logger = "0.5"
qstring = "0.7.2"
rand = "0.8"
rangemap = "1.5.1"
rb = "0.4.1"
regex = "1.10.4"
reqwest = { version = "0.12.4", default-features = false, features = [
    "blocking",
    "rustls-tls",
    "stream",
] }
rubato = "=0.12.0"
rupnp = { version = "2.0.0", features = ["full_device_spec"] }
rusqlite = { version = "0.31.0", features = ["bundled"] }
rustls = "0.23"
serde = { version = "1", features = ["derive"] }
serde-aux = "4.5.0"
serde_json = "1.0.117"
serial_test = "3.1.1"
sha2 = "0.10.8"
sqlx = { version = "0.7", default-features = false, features = [
    "runtime-tokio",
    "tls-rustls",
] }
sqlx-mysql = { version = "0.7", default-features = false, features = [
    "chrono",
] }
sqlx-postgres = { version = "0.7", default-features = false, features = [
    "chrono",
] }
static_init = "1.0.3"
strum = "0.26.2"
strum_macros = "0.26.2"
symphonia = { git = "https://github.com/pdeljanov/Symphonia", branch = "master", features = [
    "all",
] }
tantivy = "0.22.0"
test-log = "0.2.16"
thiserror = "1.0.61"
throttle = "0.1.0"
tokio = { version = "1.37.0", features = ["io-util", "sync"] }
tokio-postgres = { version = "0.7.10", features = ["with-chrono-0_4"] }
tokio-stream = "0.1.15"
tokio-tungstenite = { version = "0.21.0", features = ["native-tls-vendored"] }
tokio-util = "0.7.11"
url = "2.5.0"
uuid = { version = "1.8.0", features = ["v4"] }
webp = "0.3.0"
xml = "0.8.20"
