[workspace]
members = [
    "server",
    "packages/core",
    "packages/files",
    "packages/menu",
    "packages/ws",
]

resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
chrono = { version = "0.4.20", default-features = false, features = ["clock", "serde"] }
derive_more = "0.99.7"
dotenv = "0.15"
env_logger = "0.10"
futures-util = { version = "0.3.17", default-features = false, features = ["std"] }
log = "0.4"
openssl = { version = "0.10.55", features = ["v110"] }
rand = "0.8"
rustls = "0.21"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1.24.2", features = ["sync", "io-util"] }
tokio-util = "0.7.4"

