[package]
name = "slimmerserver"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-cors = "0.6.4"
awc = "3.0.0-beta.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.105"
futures = "0.3"
enum-as-inner = "0.6.0"
