[workspace]
members = [
    "server",
    "packages/core",
    "packages/files",
    "packages/menu",
    "packages/player",
    "packages/ws",
    "players/symphonia_player",
]

resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
chrono = { version = "0.4.20", default-features = false, features = ["clock", "serde"] }
clap = "3.1.0"
crossbeam-channel = "0.5.8"
derive_more = "0.99.7"
dotenv = "0.15"
env_logger = "0.10"
futures = "0.3"
futures-util = { version = "0.3.17", default-features = false, features = ["std"] }
lazy_static = "1.4.0"
log = { version = "0.4", features = ["release_max_level_info"] }
openssl = { version = "0.10.55", features = ["v110"] }
pretty_env_logger = "0.4"
rand = "0.8"
rangemap = "1.3.0"
reqwest = { version = "0.11.20", features = ["blocking", "stream"] }
rusqlite = { version = "0.29.0", features = ["bundled"] }
rustls = "0.21"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
symphonia = { version = "0.5.2", features = ["all"] }
tokio = { version = "1.24.2", features = ["sync", "io-util"] }
tokio-util = "0.7.4"
async-trait = "0.1.74"
