[workspace]
members = [
    "server",
    "tunnel_server",
    "packages/auth",
    "packages/config",
    "packages/converter",
    "packages/core",
    "packages/env_utils",
    "packages/files",
    "packages/image",
    "packages/json_utils",
    "packages/menu",
    "packages/player",
    "packages/qobuz",
    "packages/scan",
    "packages/search",
    "packages/stream_utils",
    "packages/tidal",
    "packages/tunnel",
    "packages/ws",
    "players/symphonia_player",
]

resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
actix = "0.13.1"
actix-cors = "0.6.5"
actix-files = "0.6.2"
actix-rt = "2.9.0"
actix-web = "4.4.1"
actix-ws = "0.2.5"
arrayvec = "0.7.1"
async-once-cell = "0.5.3"
async-trait = "0.1.74"
atomic_float = "0.1.0"
audiopus = "0.2.0"
audiotags = { git = "https://github.com/BSteffaniak/audiotags.git", branch = "master" }
awc = "3.3.0"
aws-config = "0.101.0"
aws-sdk-apigatewaymanagement = "0.38.0"
aws-sdk-ssm = "0.38.0"
base64 = "0.21.5"
bytes = "1.5.0"
chrono = { version = "0.4.20", default-features = false, features = [
    "clock",
    "serde",
] }
clap = "3.1.0"
cpal = "0.15.2"
crossbeam-channel = "0.5.8"
derive_more = "0.99.7"
dotenv = "0.15"
enum-as-inner = "0.6.0"
env_logger = "0.10"
fdk-aac = "0.5.0"
futures = "0.3"
futures-channel = "0.3.29"
futures-util = { version = "0.3.17", default-features = false, features = [
    "std",
] }
hex = "0.4.3"
home = "0.5.9"
image = "0.24.7"
io-streams = "0.15.0"
kanal = "0.1.0-pre8"
lazy_static = "1.4.0"
libpulse-binding = "2.28.1"
libpulse-simple-binding = "2.28.1"
libvips = { git = "https://github.com/BSteffaniak/libvips-rust-bindings.git", branch = "support-windows" }
lofty = { git = "https://github.com/BSteffaniak/lofty-rs.git", branch = "master" }
log = { version = "0.4", features = ["release_max_level_trace"] }
md5 = "0.7.0"
mp3-duration = "0.1.10"
mp3lame-encoder = "0.1.4"
mysql = { version = "24.0.0", features = [
    "default-rustls",
    "rustls-tls",
], default-features = false }
mysql_common = { version = "0.30", default-features = false }
ogg = "0.9.0"
once_cell = { version = "1.18.0" }
open = "5.0.1"
openssl = { version = "0.10.55", features = ["v110"] }
opus = "0.3.0"
pretty_assertions = "1.4.0"
pretty_env_logger = "0.4"
qstring = "0.7.2"
rand = "0.8"
rangemap = "1.3.0"
rb = "0.4.1"
regex = "1.9.5"
reqwest = { version = "0.11.20", features = ["blocking", "stream"] }
rubato = "0.12.0"
rusqlite = { version = "0.29.0", features = ["bundled"] }
rustls = "0.21"
serde = { version = "1", features = ["derive"] }
serde-aux = "4.2.0"
serde_json = "1.0.107"
serial_test = "3.0.0"
sha2 = "0.10.8"
static_init = "1.0.3"
strum = "0.25.0"
strum_macros = "0.25.3"
symphonia = { version = "0.5.2", features = ["all"] }
tantivy = "0.21.1"
test-log = "0.2.14"
thiserror = "1.0.48"
tokio = { version = "1.24.2", features = ["sync", "io-util"] }
tokio-stream = "0.1.14"
tokio-tungstenite = { version = "0.20.1", features = ["native-tls-vendored"] }
tokio-util = "0.7.4"
url = "2.5.0"
uuid = { version = "1.6.1", features = ["v4"] }
webp = "0.2.6"
