[workspace]
members = [
    "server",
    "tunnel_server",
    "packages/core",
    "packages/files",
    "packages/image",
    "packages/menu",
    "packages/player",
    "packages/tunnel",
    "packages/ws",
    "players/symphonia_player",
]

resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
actix = "0.13.1"
actix-cors = "0.6.4"
actix-files = "0.6.2"
actix-rt = "2.9.0"
actix-web = "4.4.0"
actix-ws = "0.2.5"
async-once-cell = "0.5.3"
async-trait = "0.1.74"
audiotags = { git = "https://github.com/BSteffaniak/audiotags.git", branch = "bug/fix-track-no" }
awc = "3.0.0-beta.9"
aws-config = "0.101.0"
aws-sdk-apigatewaymanagement = "0.38.0"
aws-sdk-ssm = "0.38.0"
aws_lambda_events = "0.11.1"
base64 = "0.21.5"
bytes = "1.5.0"
chrono = { version = "0.4.20", default-features = false, features = [
    "clock",
    "serde",
] }
clap = "3.1.0"
crossbeam-channel = "0.5.8"
derive_more = "0.99.7"
dotenv = "0.15"
enum-as-inner = "0.6.0"
env_logger = "0.10"
futures = "0.3"
futures-channel = "0.3.29"
futures-util = { version = "0.3.17", default-features = false, features = [
    "std",
] }
hex = "0.4.3"
image = "0.24.7"
io-streams = "0.15.0"
lambda-web = { version = "0.2.1", features = ["actix4"] }
lambda_runtime = "0.8.2"
lazy_static = "1.4.0"
libvips = { git = "https://github.com/BSteffaniak/libvips-rust-bindings.git", branch = "support-windows" }
log = { version = "0.4", features = ["release_max_level_trace"] }
mysql = { version = "24.0.0", features = [
    "default-rustls",
    "rustls-tls",
], default-features = false }
once_cell = { version = "1.18.0" }
openssl = { version = "0.10.55", features = ["v110"] }
pretty_env_logger = "0.4"
qstring = "0.7.2"
rand = "0.8"
rangemap = "1.3.0"
reqwest = { version = "0.11.20", features = ["blocking", "stream"] }
rusqlite = { version = "0.29.0", features = ["bundled"] }
rustls = "0.21"
serde = { version = "1", features = ["derive"] }
serde-aux = "4.2.0"
serde_json = "1.0.107"
sha2 = "0.10.8"
strum = "0.25.0"
strum_macros = "0.25.3"
symphonia = { version = "0.5.2", features = ["all"] }
thiserror = "1.0.48"
tokio = { version = "1.24.2", features = ["sync", "io-util"] }
tokio-tungstenite = { version = "0.20.1", features = ["native-tls-vendored"] }
tokio-util = "0.7.4"
url = "2.5.0"
uuid = { version = "1.6.1", features = ["v4"] }
webp = "0.2.6"
