allowed-duplicate-crates = [
    "audiopus_sys",
    "base64",
    "bitflags",
    "core-foundation",
    "crc",
    "crc-catalog",
    "env_logger",
    "fallible-iterator",
    "glow",
    "h2",
    "hashbrown",
    "hashlink",
    "heck",
    "http",
    "http-body",
    "hyper",
    "hyper-rustls",
    "indexmap",
    "itertools",
    "miniz_oxide",
    "mio",
    "ndk-sys",
    "num-derive",
    "regex-automata",
    "regex-syntax",
    "reqwest",
    "roxmltree",
    "rustc-hash",
    "rustls",
    "rustls-pemfile",
    "rustls-webpki",
    "spin",
    "syn",
    "sync_wrapper",
    "tokio-rustls",
    "toml_edit",
    "tower",
    "webpki-roots",
    "winapi",
    "windows",
    "windows-core",
    "windows-result",
    "windows-sys",
    "windows-target",
    "windows-targets",
    "windows_aarch64_gnullvm",
    "windows_aarch64_msvc",
    "windows_aarch_msvc",
    "windows_i686_gnu",
    "windows_i686_msvc",
    "windows_x86_64_gnu",
    "windows_x86_64_gnullvm",
    "windows_x86_64_msvc",
    "winnow",
    "winreg",
    "zerocopy",
    "zerocopy-derive",
]
