allowed-duplicate-crates = [
    "audiopus_sys",
    "base64",
    "bitflags",
    "env_logger",
    "fallible-iterator",
    "hashlink",
    "heck",
    "http",
    "http-body",
    "hyper",
    "hyper-rustls",
    "num-derive",
    "regex-automata",
    "regex-syntax",
    "reqwest",
    "rustls",
    "rustls-pemfile",
    "rustls-webpki",
    "spin",
    "syn",
    "tokio-rustls",
    "toml_edit",
    "webpki-roots",
    "windows",
    "windows-core",
    "windows-sys",
    "windows-target",
    "windows-targets",
    "windows_aarch64_gnullvm",
    "windows_aarch64_msvc",
    "windows_aarch_msvc",
    "windows_i686_gnu",
    "windows_i686_msvc",
    "windows_x86_64_gnu",
    "windows_x86_64_gnullvm",
    "windows_x86_64_msvc",
    "winnow",
    "winreg",
]
