services:
    moosicbox-server:
        image: moosicbox-server
        build:
            context: .
            dockerfile: packages/server/Server.Dockerfile
            args:
                WS_HOST: "${WS_HOST}"
                TUNNEL_ACCESS_TOKEN: "${TUNNEL_ACCESS_TOKEN}"
                STATIC_TOKEN: "${STATIC_TOKEN}"
        ports:
            - "8010:8010"

    moosicbox-tunnel-server:
        image: moosicbox-tunnel-server
        build:
            context: .
            dockerfile: packages/tunnel_server/TunnelServer.Dockerfile
            args:
                TUNNEL_ACCESS_TOKEN: "${TUNNEL_ACCESS_TOKEN}"
        ports:
            - "8004:8004"
