[package]
authors     = ["Braden Steffaniak"]
categories  = ["development-tools"]
description = "MoosicBox audio zone package"
edition     = "2021"
keywords    = ["audio", "group", "grouping", "playback"]
license     = "MPL-2.0"
name        = "moosicbox_audio_zone"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBox"
version     = "0.1.0"

[dependencies]
moosicbox_assert = { path = "../assert", default-features = false }
moosicbox_core = { path = "../core", default-features = false }
moosicbox_database = { path = "../database", default-features = false }
moosicbox_json_utils = { path = "../json_utils", default-features = false, features = [
    "database",
] }

# API Dependencies
actix-web        = { workspace = true, optional = true }
moosicbox_paging = { path = "../paging", optional = true }
utoipa           = { workspace = true, optional = true }

# Events Dependencies
moosicbox_task = { path = "../task", default-features = false, optional = true }

async-trait = { workspace = true }
log         = { workspace = true }
serde       = { workspace = true }
tokio       = { workspace = true, features = ["rt-multi-thread", "tracing"] }

[features]
default = ["api", "events", "openapi"]

fail-on-warnings = []

api     = ["dep:actix-web", "dep:moosicbox_paging", "moosicbox_database/api"]
openapi = ["dep:utoipa", "moosicbox_paging/openapi"]

events = ["dep:moosicbox_task"]
