[package]
authors     = ["Braden Steffaniak"]
categories  = ["development-tools"]
description = "MoosicBox menu models package"
edition     = "2021"
keywords    = ["album", "artist", "menu", "playlist", "track"]
license     = "MPL-2.0"
name        = "moosicbox_menu_models"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBox"
version     = "0.1.0"

[dependencies]
moosicbox_assert = { version = "0.1.0", path = "../../assert", default-features = false }
moosicbox_core   = { version = "0.1.0", path = "../../core", default-features = false }

# API Dependencies
utoipa = { workspace = true, optional = true }

log   = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[features]
default = ["all-sources", "api", "openapi"]

fail-on-warnings = []

api     = []
openapi = ["dep:utoipa", "moosicbox_core/openapi"]

all-sources = ["qobuz", "tidal", "yt"]

qobuz = ["moosicbox_core/qobuz"]
tidal = ["moosicbox_core/tidal"]
yt    = ["moosicbox_core/yt"]
