[package]
authors     = ["Braden Steffaniak"]
categories  = ["gui"]
description = "MoosicBoxApp bundled package"
edition     = "2021"
keywords    = ["bundled"]
license     = "MPL-2.0"
name        = "moosicbox_app_bundled"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBoxServer"
version     = "0.1.0"

[package.metadata.cargo-machete]
ignored = ["strum", "thiserror"]

[dependencies]
moosicbox_assert = { path = "../../assert", default-features = false }
moosicbox_async_service = { path = "../../async_service", default-features = false }
moosicbox_config = { path = "../../config", default-features = false }
moosicbox_server = { path = "../../server", default-features = false, features = [
    "app-apis",
    "sqlite-sqlx",
] }
moosicbox_task = { path = "../../task", default-features = false }

log          = { workspace = true }
strum        = { workspace = true }
strum_macros = { workspace = true }
tauri        = { workspace = true }
thiserror    = { workspace = true }
tokio        = { workspace = true }

[features]
default = []

fail-on-warnings = []

tunnel = ["moosicbox_server/tunnel"]

# Encoders
aac  = ["moosicbox_server/aac"]
flac = ["moosicbox_server/flac"]
mp3  = ["moosicbox_server/mp3"]
