[package]
authors     = ["Braden Steffaniak"]
categories  = ["network-programming"]
default-run = "moosicbox_tunnel_server"
description = "MoosicBox tunnel server package"
edition     = "2021"
keywords    = ["api", "server", "tunnel", "websocket"]
license     = "MPL-2.0"
name        = "moosicbox_tunnel_server"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBoxServer"
version     = "0.1.0"

[[bin]]
name = "moosicbox_tunnel_server"
path = "src/main.rs"

[dependencies]
moosicbox_assert        = { path = "../assert", default-features = false }
moosicbox_async_service = { path = "../async_service", default-features = false }
moosicbox_database      = { path = "../database", default-features = false }
moosicbox_env_utils     = { path = "../env_utils" }
moosicbox_json_utils    = { path = "../json_utils" }
moosicbox_logging       = { path = "../logging" }
moosicbox_middleware    = { path = "../middleware", default-features = false }
moosicbox_task          = { path = "../task", default-features = false }
moosicbox_tunnel        = { path = "../tunnel", default-features = false }

sqlx = { workspace = true, optional = true, features = [
    "postgres",
    "runtime-tokio",
    "tls-rustls",
] }

native-tls          = { workspace = true, optional = true }
openssl             = { workspace = true, optional = true }
postgres-native-tls = { workspace = true, optional = true }
postgres-openssl    = { workspace = true, optional = true }
tokio-postgres      = { workspace = true, optional = true }

actix-cors = { workspace = true }
actix-web = { workspace = true }
actix-ws = { workspace = true }
aws-config = { workspace = true }
aws-sdk-ssm = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
console-subscriber = { workspace = true }
env_logger = { workspace = true }
flume = { workspace = true }
futures-util = { workspace = true }
hex = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }
once_cell = { workspace = true }
qstring = { workspace = true }
rand = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha2 = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = [
    "macros",
    "rt-multi-thread",
    "tracing",
] }
tokio-util = { workspace = true }
uuid = { workspace = true }

[features]
default = [
    "base64",
    "postgres",
    "postgres-native-tls",
    "postgres-openssl",
    "postgres-raw",
    "postgres-sqlx",
]

fail-on-warnings = []

base64 = ["moosicbox_tunnel/base64"]

postgres = ["moosicbox_database/postgres"]
postgres-native-tls = ["dep:native-tls", "dep:postgres-native-tls"]
postgres-openssl = ["dep:native-tls", "dep:openssl", "dep:postgres-openssl"]
postgres-raw = [
    "dep:tokio-postgres",
    "moosicbox_database/postgres-raw",
    "postgres",
]
postgres-sqlx = ["dep:sqlx", "moosicbox_database/postgres-sqlx", "postgres"]
