[package]
authors     = ["Braden Steffaniak"]
categories  = ["development-tools", "multimedia", "network-programming"]
description = "MoosicBox Library Music API models package"
edition     = "2021"
keywords    = ["audio", "library", "models"]
license     = "MPL-2.0"
name        = "moosicbox_library_models"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBox"
version     = "0.1.0"

[dependencies]
moosicbox_core = { path = "../../core", default-features = false }
moosicbox_database = { path = "../../database", optional = true, default-features = false }
moosicbox_json_utils = { path = "../../json_utils", default-features = false, features = [
    "serde_json",
] }

# API Dependencies
utoipa = { workspace = true, optional = true }

async-trait = { workspace = true, optional = true }
log         = { workspace = true }
serde       = { workspace = true, features = ["derive"] }
serde_json  = { workspace = true }

[features]
default = ["all-formats", "api", "db", "openapi"]

fail-on-warnings = []

api     = ["moosicbox_database/api"]
openapi = ["dep:utoipa", "moosicbox_core/openapi"]

db = [
    "dep:async-trait",
    "dep:moosicbox_database",
    "moosicbox_json_utils/database",
]

all-formats = ["aac", "flac", "mp3", "opus"]

aac  = ["moosicbox_core/aac"]
flac = ["moosicbox_core/flac"]
mp3  = ["moosicbox_core/mp3"]
opus = ["moosicbox_core/opus"]
