[package]
authors     = ["Braden Steffaniak"]
categories  = ["development-tools", "multimedia", "network-programming"]
description = "MoosicBox Library Music API models package"
edition     = "2021"
keywords    = ["audio", "library", "models"]
license     = "MPL-2.0"
name        = "moosicbox_library_models"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBox"
version     = "0.1.0"

[package.metadata.cargo-machete]
ignored = ["strum_macros"]

[dependencies]
moosicbox_assert = { version = "0.1.0", path = "../../assert", default-features = false }
moosicbox_core = { version = "0.1.0", path = "../../core", default-features = false }
moosicbox_database = { version = "0.1.0", path = "../../database", optional = true, default-features = false }
moosicbox_json_utils = { version = "0.1.0", path = "../../json_utils", default-features = false, features = [
    "serde_json",
] }
moosicbox_qobuz = { version = "0.1.0", path = "../../qobuz", optional = true, default-features = false, features = [
    "api",
] }
moosicbox_tidal = { version = "0.1.0", path = "../../tidal", optional = true, default-features = false, features = [
    "api",
] }
moosicbox_yt = { version = "0.1.0", path = "../../yt", optional = true, default-features = false, features = [
    "api",
] }

# API Dependencies
utoipa = { workspace = true, optional = true }

async-trait  = { workspace = true, optional = true }
log          = { workspace = true }
serde        = { workspace = true, features = ["derive"] }
serde_json   = { workspace = true }
strum        = { workspace = true, features = ["derive"] }
strum_macros = { workspace = true }
thiserror    = { workspace = true }

[features]
default = ["all-formats", "all-sources", "api", "db", "openapi"]

fail-on-warnings = []

api     = ["moosicbox_database/api"]
openapi = ["dep:utoipa", "moosicbox_core/openapi"]

db = [
    "dep:async-trait",
    "dep:moosicbox_database",
    "moosicbox_json_utils/database",
]

all-formats = ["aac", "flac", "mp3", "opus"]

aac  = ["moosicbox_core/aac"]
flac = ["moosicbox_core/flac"]
mp3  = ["moosicbox_core/mp3"]
opus = ["moosicbox_core/opus"]

all-sources = ["qobuz", "tidal", "yt"]

qobuz = ["dep:moosicbox_qobuz", "moosicbox_core/qobuz"]
tidal = ["dep:moosicbox_tidal", "moosicbox_core/tidal"]
yt    = ["dep:moosicbox_yt", "moosicbox_core/yt"]
