[package]
authors     = ["Braden Steffaniak"]
categories  = ["network-programming"]
description = "MoosicBox load balancer"
edition     = "2021"
keywords    = ["api", "balance", "balancer", "load"]
license     = "MPL-2.0"
name        = "moosicbox_load_balancer"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBoxServer"
version     = "0.1.0"

[package.metadata.cargo-machete]
ignored = ["moosicbox_env_utils"]

[[bin]]
name              = "moosicbox_lb"
path              = "src/main.rs"
required-features = []

[target.'cfg(not(target_os = "windows"))'.dependencies]
moosicbox_env_utils = { path = "../env_utils", default-features = false }
moosicbox_logging   = { path = "../logging", default-features = false }

async-trait            = { workspace = true }
log                    = { workspace = true }
pingora                = { workspace = true }
pingora-core           = { workspace = true }
pingora-http           = { workspace = true }
pingora-load-balancing = { workspace = true }
pingora-proxy          = { workspace = true }

[features]
fail-on-warnings = []
