[package]
authors     = ["Braden Steffaniak"]
categories  = ["network-programming"]
description = "MoosicBox load balancer"
edition     = "2021"
keywords    = ["api", "balance", "balancer", "load"]
license     = "MPL-2.0"
name        = "moosicbox_load_balancer"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBoxServer"
version     = "0.1.0"

[dependencies]
moosicbox_assert = { path = "../assert", default-features = false }

pingora = { workspace = true }

[features]
fail-on-warnings = []
