[[config]]
os = "ubuntu"

[[config.dependencies]]
command  = 'sudo apt-get update && sudo apt-get install libvips-dev'
features = ["default", "libvips"]

[[config]]
cargo = "--bin image_helper"
name  = "image-bin"
os    = "ubuntu"

[[config.dependencies]]
command  = 'sudo apt-get update && sudo apt-get install libvips-dev'
features = ["default", "libvips"]
