[package]
authors     = ["Braden Steffaniak"]
categories  = ["development-tools", "gui", "web-programming"]
description = "GigaChad package"
edition     = "2021"
keywords    = ["gigachad"]
license     = "MPL-2.0"
name        = "gigachad"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBox"
version     = "0.1.0"

[dependencies]
gigachad_transformer = { version = "0.1.0", path = "transformer", default-features = false }

[features]
fail-on-warnings = []
