[package]
name = "moosicbox_symphonia_player"
version = "0.1.0"
authors = ["Braden Steffaniak"]
edition = "2021"

[dependencies]
clap = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }
pretty_env_logger = { workspace = true }
symphonia = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
libpulse-binding = "2.5.0"
libpulse-simple-binding = "2.5.0"

[target.'cfg(not(target_os = "linux"))'.dependencies]
arrayvec = "0.7.1"
cpal = "0.13.3"
rb = "0.3.2"
rubato = "0.12.0"

[features]
fail-on-warnings = []
