[package]
authors     = ["Braden Steffaniak"]
categories  = ["database"]
description = "MoosicBox schema package"
edition     = "2021"
keywords    = ["database", "schema", "sqlite"]
license     = "MPL-2.0"
name        = "moosicbox_schema"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBoxServer"
version     = "0.1.0"

[dependencies]
moosicbox_assert = { path = "../assert", default-features = false }

diesel            = { workspace = true, default-features = false }
diesel_migrations = { workspace = true, default-features = false }
thiserror         = { workspace = true }

[features]
default = ["sqlite"]

fail-on-warnings = []

mysql    = ["diesel/mysql", "diesel_migrations/mysql"]
postgres = ["diesel/postgres", "diesel_migrations/postgres"]
sqlite   = ["diesel/sqlite", "diesel_migrations/sqlite"]
