[package]
authors     = ["Braden Steffaniak"]
categories  = ["database"]
description = "MoosicBox database package"
edition     = "2021"
keywords    = ["database", "mysql", "postgres", "sqlite"]
license     = "MPL-2.0"
name        = "moosicbox_database"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBoxServer"
version     = "0.1.0"

[dependencies]
moosicbox_assert = { path = "../assert", default-features = false }
moosicbox_task   = { path = "../task", default-features = false }

# DB Dependencies
rusqlite = { workspace = true, optional = true }

# sqlx dependencies
sqlx          = { workspace = true, optional = true, features = ["runtime-tokio"] }
sqlx-mysql    = { workspace = true, optional = true }
sqlx-postgres = { workspace = true, optional = true }

# tokio-postgres dependencies
postgres-protocol = { workspace = true, optional = true, features = [] }
tokio-postgres    = { workspace = true, optional = true, features = [] }

# Postgres dependencies
regex = { workspace = true, optional = true }

# Api dependencies
actix-web = { workspace = true, optional = true }
qstring   = { workspace = true, optional = true }

async-recursion = { workspace = true }
async-trait     = { workspace = true }
chrono          = { workspace = true }
futures         = { workspace = true }
log             = { workspace = true }
serde           = { workspace = true, features = ["derive"] }
serde_json      = { workspace = true }
strum           = { workspace = true }
strum_macros    = { workspace = true }
thiserror       = { workspace = true }
tokio           = { workspace = true, features = ["macros", "rt", "tracing"] }
tokio-util      = { workspace = true }

[features]
default = ["api", "mysql", "postgres-sqlx", "sqlite-sqlx"]

fail-on-warnings = []

tls = ["sqlx/tls-rustls"]

api = ["dep:actix-web", "dep:qstring"]

mysql = ["mysql-sqlx", "sqlx"]
mysql-sqlx = [
    "dep:sqlx",
    "dep:sqlx-mysql",
    "sqlx",
    "sqlx-mysql/chrono",
    "sqlx/mysql",
]
postgres = ["dep:regex", "postgres-raw"]
postgres-raw = ["dep:postgres-protocol", "dep:tokio-postgres", "postgres"]
postgres-sqlx = [
    "dep:sqlx",
    "dep:sqlx-postgres",
    "postgres",
    "sqlx",
    "sqlx-postgres/chrono",
    "sqlx/postgres",
]
sqlite = ["sqlite-sqlx"]
sqlite-rusqlite = ["dep:rusqlite"]
sqlite-sqlx = ["dep:regex", "dep:sqlx", "sqlx", "sqlx/sqlite"]
sqlx = []
