[package]
authors     = ["Braden Steffaniak"]
categories  = ["database"]
description = "MoosicBox database package"
edition     = "2021"
keywords    = ["database", "mysql", "postgres", "sqlite"]
license     = "MPL-2.0"
name        = "moosicbox_database"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBoxServer"
version     = "0.1.0"

[dependencies]
# DB Dependencies
rusqlite = { workspace = true, optional = true }

# sqlx dependencies
sqlx = { workspace = true, optional = true, features = [
    "runtime-tokio",
    "tls-rustls",
] }
sqlx-mysql = { workspace = true, optional = true }
sqlx-postgres = { workspace = true, optional = true }

# tokio-postgres dependencies
postgres-protocol = { workspace = true, optional = true, features = [] }
tokio-postgres    = { workspace = true, optional = true, features = [] }

# Postgres dependencies
regex = { workspace = true, optional = true }

async-recursion = { workspace = true }
async-trait     = { workspace = true }
chrono          = { workspace = true }
futures         = { workspace = true }
log             = { workspace = true }
once_cell       = { workspace = true }
serde           = { workspace = true, features = ["derive"] }
serde_json      = { workspace = true }
strum           = { workspace = true }
strum_macros    = { workspace = true }
thiserror       = { workspace = true }
tokio           = { workspace = true, features = ["macros"] }
tokio-util      = { workspace = true }

[features]
default = ["mysql", "postgres", "rusqlite"]

fail-on-warnings = []

mysql = ["mysql-sqlx", "sqlx"]
mysql-sqlx = [
    "dep:sqlx",
    "dep:sqlx-mysql",
    "sqlx",
    "sqlx-mysql/chrono",
    "sqlx/mysql",
]
postgres = ["dep:regex", "postgres-raw"]
postgres-raw = ["dep:postgres-protocol", "dep:tokio-postgres", "postgres"]
postgres-sqlx = [
    "dep:sqlx",
    "dep:sqlx-postgres",
    "postgres",
    "sqlx",
    "sqlx-postgres/chrono",
    "sqlx/postgres",
]
rusqlite = ["dep:rusqlite"]
sqlx = []
