[package]
authors = ["Braden Steffaniak"]
edition = "2021"
name    = "moosicbox_database"
version = "0.1.0"

[dependencies]
moosicbox_core = { path = "../core", default-features = false }
moosicbox_json_utils = { path = "../json_utils", default-features = false, features = [
    "serde_json",
] }
moosicbox_paging = { path = "../paging", default-features = false }

# DB Dependencies
rusqlite = { workspace = true, optional = true }

async-recursion = { workspace = true }
async-trait     = { workspace = true }
futures         = { workspace = true }
log             = { workspace = true }
once_cell       = { workspace = true }
serde           = { workspace = true, features = ["derive"] }
serde_json      = { workspace = true }
strum           = { workspace = true }
strum_macros    = { workspace = true }
thiserror       = { workspace = true }
tokio           = { workspace = true, features = ["macros"] }
tokio-util      = { workspace = true }

[features]
default = ["rusqlite"]

fail-on-warnings = []

rusqlite = ["dep:rusqlite"]
