[package]
authors     = ["Braden Steffaniak"]
categories  = ["gui"]
description = "MoosicBox"
edition     = "2021"
keywords    = ["app", "desktop", "gui"]
license     = "MPL-2.0"
name        = "moosicbox_app"
publish     = []
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBox"
version     = "0.14.0"

[package.metadata.workspaces]
independent = true

[package.metadata.cargo-machete]
ignored = ["strum", "tauri-build"]

[lib]
crate-type = ["cdylib", "rlib", "staticlib"]
name       = "moosicbox_lib"

[build-dependencies]
tauri-build = { workspace = true, features = [] }

[dependencies]
moosicbox_app_state = { version = "0.1.0", path = "../../state", default-features = false, features = [
    "upnp",
] }

moosicbox_assert = { version = "0.1.0", path = "../../../assert", default-features = false }
moosicbox_audio_zone = { version = "0.1.0", path = "../../../audio_zone", default-features = false }
moosicbox_core = { version = "0.1.0", path = "../../../core", default-features = false }
moosicbox_env_utils = { version = "0.1.0", path = "../../../env_utils", default-features = false }
moosicbox_library = { version = "0.1.0", path = "../../../library", default-features = false }
moosicbox_logging = { version = "0.1.0", path = "../../../logging", default-features = false, features = [
    "free_log",
] }
moosicbox_mdns = { version = "0.1.0", path = "../../../mdns", default-features = false, features = [
    "scanner",
] }
moosicbox_music_api = { version = "0.1.0", path = "../../../music_api", default-features = false }
moosicbox_paging = { version = "0.1.0", path = "../../../paging", default-features = false }
moosicbox_player = { version = "0.1.0", path = "../../../player", default-features = false, features = [
    "local",
] }
moosicbox_session = { version = "0.1.0", path = "../../../session", default-features = false }
moosicbox_task = { version = "0.1.0", path = "../../../task", default-features = false }
moosicbox_upnp = { version = "0.1.0", path = "../../../upnp", default-features = false, features = [
    "player",
] }
moosicbox_ws = { version = "0.1.0", path = "../../../ws", default-features = false }

# Bundled Dependencies
moosicbox_app_tauri_bundled = { version = "0.1.0", path = "../bundled", default-features = false, optional = true }

# Client Dependencies
moosicbox_app_client = { version = "0.1.0", path = "../client", default-features = false, optional = true }

app-tauri-plugin-player = { version = "0.1.0", path = "../tauri-plugin-player" }

console-subscriber        = { workspace = true }
kanal                     = { workspace = true }
lazy_static               = { workspace = true }
log                       = { workspace = true }
serde                     = { workspace = true, features = ["derive"] }
serde_json                = { workspace = true }
strum                     = { workspace = true }
strum_macros              = { workspace = true }
tauri                     = { workspace = true, features = ["protocol-asset"] }
tauri-plugin-dialog       = { workspace = true }
tauri-plugin-notification = { workspace = true }
thiserror                 = { workspace = true }
tokio                     = { workspace = true, features = ["macros"] }

[features]
default = ["all-supported-formats", "cpal"]

fail-on-warnings = []

# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

android = []
desktop = ["all-encoders", "moosicbox_app_tauri_bundled?/tunnel"]

all-encoders = ["aac", "flac", "mp3"]

bundled = ["dep:moosicbox_app_tauri_bundled"]
client  = ["dep:moosicbox_app_client"]

all-supported-formats = ["aac", "flac", "mp3"]

# Encoders
aac  = ["moosicbox_app_tauri_bundled?/aac", "moosicbox_core/aac"]
flac = ["moosicbox_app_tauri_bundled?/flac", "moosicbox_core/flac"]
mp3  = ["moosicbox_app_tauri_bundled?/mp3", "moosicbox_core/mp3"]

# Player audio outputs
asio                = ["moosicbox_player/asio"]
cpal                = ["moosicbox_player/cpal", "moosicbox_player/oboe-shared-stdcxx"]
jack                = ["moosicbox_player/jack"]
pulseaudio          = ["moosicbox_player/pulseaudio"]
pulseaudio-simple   = ["moosicbox_player/pulseaudio-simple"]
pulseaudio-standard = ["moosicbox_player/pulseaudio-standard"]

devtools = ["tauri/devtools"]
