[package]
authors = ["Braden Steffaniak"]
edition = "2021"
name    = "moosicbox_auth"
version = "0.1.0"

[dependencies]
moosicbox_core       = { path = "../core", default-features = false }
moosicbox_json_utils = { path = "../json_utils", default-features = false, features = [
    "serde_json",
] }

actix      = { workspace = true }
actix-web  = { workspace = true }
log        = { workspace = true }
reqwest    = { workspace = true, features = ["json"] }
rusqlite   = { workspace = true }
serde      = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror  = { workspace = true }
url        = { workspace = true }
uuid       = { workspace = true }

[features]
default = ["api"]

fail-on-warnings = []

api = []
