[package]
authors = ["Braden Steffaniak"]
edition = "2021"
name    = "moosicbox_auth"
version = "0.1.0"

[dependencies]
actix-web      = { workspace = true }
log            = { workspace = true }
moosicbox_core = { path = "../core" }
reqwest        = { workspace = true, features = ["json"] }
rusqlite       = { workspace = true }
serde          = { workspace = true, features = ["derive"] }
serde_json     = { workspace = true }
thiserror      = { workspace = true }
uuid           = { workspace = true }

[features]
default = ["api"]

fail-on-warnings = []

api = []
