[package]
authors     = ["Braden Steffaniak"]
categories  = ["authentication"]
description = "MoosicBox authentication package"
edition     = "2021"
keywords    = ["authentication", "token"]
license     = "MPL-2.0"
name        = "moosicbox_auth"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBoxServer"
version     = "0.1.0"

[dependencies]
moosicbox_core = { path = "../core", default-features = false }
moosicbox_database = { path = "../database", default-features = false, features = [
    "sqlite-sqlx",
] }
moosicbox_json_utils = { path = "../json_utils", default-features = false, features = [
    "serde_json",
] }

# API Dependencies
utoipa = { workspace = true, optional = true }

actix      = { workspace = true }
actix-web  = { workspace = true }
log        = { workspace = true }
reqwest    = { workspace = true, features = ["json"] }
serde      = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror  = { workspace = true }
url        = { workspace = true }
uuid       = { workspace = true }

[features]
default = ["api", "openapi"]

fail-on-warnings = []

api     = ["moosicbox_database/api"]
openapi = ["dep:utoipa"]
