[package]
authors     = ["Braden Steffaniak"]
categories  = ["development-tools"]
description = "MoosicBox audio outputs package"
edition     = "2021"
keywords    = ["audio", "cpal", "outputs", "pulse", "pulseaudio"]
license     = "MPL-2.0"
name        = "moosicbox_audio_output"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBoxServer"
version     = "0.1.0"

[dependencies]
moosicbox_assert        = { path = "../assert", default-features = false }
moosicbox_audio_decoder = { path = "../audio_decoder", default-features = false }
moosicbox_env_utils     = { path = "../env_utils", default-features = false }
moosicbox_resampler     = { path = "../resampler", default-features = false }
moosicbox_stream_utils  = { path = "../stream_utils", default-features = false }
moosicbox_task          = { path = "../task", default-features = false }

# API Dependencies
actix-web        = { workspace = true, optional = true }
moosicbox_paging = { path = "../paging", optional = true }
serde            = { workspace = true, optional = true }
serde_json       = { workspace = true, optional = true }
utoipa           = { workspace = true, optional = true }

# DB Dependencies
moosicbox_database   = { path = "../database", default-features = false, optional = true }
moosicbox_json_utils = { path = "../json_utils", default-features = false, optional = true }
strum                = { workspace = true, optional = true }
strum_macros         = { workspace = true, optional = true }

# CPAL
cpal = { workspace = true, optional = true }
rb   = { workspace = true, optional = true }

# PulseAudio
libpulse-binding        = { workspace = true, optional = true }
libpulse-simple-binding = { workspace = true, optional = true }

# Encoders
fdk-aac                 = { workspace = true, optional = true }
moosicbox_audio_encoder = { path = "../audio_encoder", default-features = false, optional = true }
mp3lame-encoder         = { workspace = true, optional = true }
ogg                     = { workspace = true, optional = true }
opus                    = { workspace = true, optional = true }

bytes      = { workspace = true }
log        = { workspace = true }
symphonia  = { workspace = true }
thiserror  = { workspace = true }
tokio      = { workspace = true, features = ["rt-multi-thread", "tracing"] }
tokio-util = { workspace = true }

[features]
default = ["api", "db", "default-windows", "openapi", "pulseaudio"]

default-windows = ["aac", "cpal", "flac", "mp3", "oboe-shared-stdcxx", "opus"]

fail-on-warnings = []

api     = ["dep:actix-web", "dep:moosicbox_paging", "dep:serde", "dep:serde_json"]
openapi = ["dep:utoipa", "moosicbox_paging/openapi"]

db = [
    "dep:moosicbox_database",
    "dep:moosicbox_json_utils",
    "dep:strum",
    "dep:strum_macros",
]

asio                = ["cpal/asio"]
cpal                = ["dep:cpal", "dep:rb"]
jack                = ["cpal/jack"]
oboe-shared-stdcxx  = ["cpal/oboe-shared-stdcxx"]
pulseaudio          = ["pulseaudio-simple", "pulseaudio-standard"]
pulseaudio-simple   = ["dep:libpulse-binding", "dep:libpulse-simple-binding"]
pulseaudio-standard = ["dep:libpulse-binding", "dep:libpulse-simple-binding"]

aac = [
    "dep:fdk-aac",
    "dep:moosicbox_audio_encoder",
    "moosicbox_audio_encoder/aac",
]
flac = ["dep:moosicbox_audio_encoder", "moosicbox_audio_encoder/flac"]
mp3 = [

    "dep:moosicbox_audio_encoder",
    "dep:mp3lame-encoder",
    "moosicbox_audio_encoder/mp3",
]
opus = [

    "dep:moosicbox_audio_encoder",
    "dep:ogg",
    "dep:opus",
    "moosicbox_audio_encoder/opus",
]
