[package]
authors     = ["Braden Steffaniak"]
categories  = ["development-tools"]
description = "MoosicBox App State package"
edition     = "2021"
keywords    = ["state"]
license     = "MPL-2.0"
name        = "moosicbox_app_state"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBox"
version     = "0.1.0"

[dependencies]
moosicbox_app_ws = { version = "0.1.0", path = "../tauri/ws", default-features = false }

moosicbox_assert = { version = "0.1.0", path = "../../assert", default-features = false }
moosicbox_audio_output = { version = "0.1.0", path = "../../audio_output", default-features = false }
moosicbox_audio_zone = { version = "0.1.0", path = "../../audio_zone", default-features = false }
moosicbox_core = { version = "0.1.0", path = "../../core", default-features = false }
moosicbox_env_utils = { version = "0.1.0", path = "../../env_utils", default-features = false }
moosicbox_music_api = { version = "0.1.0", path = "../../music_api", default-features = false }
moosicbox_player = { version = "0.1.0", path = "../../player", default-features = false, features = [
    "local",
] }
moosicbox_session = { version = "0.1.0", path = "../../session", default-features = false }
moosicbox_upnp = { version = "0.1.0", path = "../../upnp", optional = true, default-features = false, features = [
    "player",
] }
moosicbox_ws = { version = "0.1.0", path = "../../ws", default-features = false }

log        = { workspace = true }
thiserror  = { workspace = true }
tokio      = { workspace = true, features = ["macros"] }
tokio-util = { workspace = true }

[features]
default = ["upnp"]

upnp = ["dep:moosicbox_upnp"]

fail-on-warnings = []
