[package]
authors     = ["Braden Steffaniak"]
categories  = ["development-tools"]
description = "MoosicBox Session Handling package"
edition     = "2021"
keywords    = ["session", "state"]
license     = "MPL-2.0"
name        = "moosicbox_session"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBox"
version     = "0.1.0"

[package.metadata.cargo-machete]
ignored = ["strum"]

[dependencies]
moosicbox_assert     = { version = "0.1.0", path = "../assert", default-features = false }
moosicbox_audio_zone = { version = "0.1.0", path = "../audio_zone", default-features = false }
moosicbox_core       = { version = "0.1.0", path = "../core", default-features = false }
moosicbox_database   = { version = "0.1.0", path = "../database", default-features = false }
moosicbox_json_utils = { version = "0.1.0", path = "../json_utils", default-features = false }
moosicbox_library    = { version = "0.1.0", path = "../library", default-features = false }

# API Dependencies
actix-web        = { workspace = true, optional = true }
moosicbox_paging = { version = "0.1.0", path = "../paging", optional = true }
utoipa           = { workspace = true, optional = true }

# Events Dependencies
moosicbox_task = { version = "0.1.0", path = "../task", default-features = false, optional = true }
tokio          = { workspace = true, optional = true }

async-trait  = { workspace = true }
log          = { workspace = true }
serde        = { workspace = true, features = ["derive"] }
serde_json   = { workspace = true }
strum        = { workspace = true }
strum_macros = { workspace = true }

[features]
default = ["aac", "api", "events", "flac", "mp3", "openapi", "opus"]

fail-on-warnings = []

api = ["dep:actix-web", "dep:moosicbox_paging", "moosicbox_database/api"]
openapi = [
    "dep:utoipa",
    "moosicbox_audio_zone/openapi",
    "moosicbox_core/openapi",
    "moosicbox_library/openapi",
    "moosicbox_paging/openapi",
]

events = ["dep:moosicbox_task", "dep:tokio"]

aac  = ["moosicbox_library/aac"]
flac = ["moosicbox_library/flac"]
mp3  = ["moosicbox_library/mp3"]
opus = ["moosicbox_library/opus"]
