[package]
authors     = ["Braden Steffaniak"]
categories  = ["multimedia", "network-programming"]
description = "MoosicBox Remote Library Music API package"
edition     = "2021"
keywords    = ["audio", "library", "remote"]
license     = "MPL-2.0"
name        = "moosicbox_remote_library"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBoxServer"
version     = "0.1.0"

[dependencies]
moosicbox_core = { path = "../core", default-features = false }
moosicbox_music_api = { path = "../music_api", default-features = false }
moosicbox_paging = { path = "../paging", default-features = false }

async-trait  = { workspace = true }
log          = { workspace = true }
reqwest      = { workspace = true, features = ["json"] }
thiserror    = { workspace = true }

[features]
default = ["aac", "flac", "mp3", "opus"]

fail-on-warnings = []

aac  = ["moosicbox_core/aac"]
flac = ["moosicbox_core/flac"]
mp3  = ["moosicbox_core/mp3"]
opus = ["moosicbox_core/opus"]
