[package]
authors     = ["Braden Steffaniak"]
categories  = ["gui"]
description = "GigaChad HTML renderer package"
edition     = "2021"
keywords    = ["gui", "html", "render", "renderer", "web"]
license     = "MPL-2.0"
name        = "gigachad_renderer_html"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBox"
version     = "0.1.0"

[dependencies]
gigachad_renderer = { version = "0.1.0", path = "../", default-features = false, features = [
    "canvas",
    "html",
] }
gigachad_renderer_html_actix = { version = "0.1.0", path = "actix", default-features = false, optional = true }
gigachad_renderer_html_lambda = { version = "0.1.0", path = "lambda", default-features = false, optional = true }
gigachad_router = { version = "0.1.0", path = "../../../gigachad/router", default-features = false }
gigachad_transformer = { version = "0.1.0", path = "../../transformer", default-features = false, features = [
    "html",
] }
moosicbox_assert = { version = "0.1.0", path = "../../../assert", default-features = false }
moosicbox_env_utils = { version = "0.1.0", path = "../../../env_utils", default-features = false }
moosicbox_logging = { version = "0.1.0", path = "../../../logging", default-features = false, features = [
    "macros",
] }

async-trait = { workspace = true }
flume       = { workspace = true }
log         = { workspace = true }
maud        = { workspace = true }
tokio       = { workspace = true }
uaparser    = { workspace = true }

[features]
default = ["actix", "assets", "debug", "lambda"]

fail-on-warnings = []

debug = []

actix  = ["dep:gigachad_renderer_html_actix"]
lambda = ["dep:gigachad_renderer_html_lambda"]

assets = [
    "gigachad_renderer/assets",
    "gigachad_renderer_html_actix?/assets",
    "gigachad_renderer_html_lambda?/assets",
]
