[package]
authors     = ["Braden Steffaniak"]
categories  = ["network-programming"]
description = "MoosicBox websocket package"
edition     = "2021"
keywords    = ["api", "websocket"]
license     = "MPL-2.0"
name        = "moosicbox_ws"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBoxServer"
version     = "0.1.0"

[dependencies]
moosicbox_assert = { path = "../assert", default-features = false }
moosicbox_audio_zone = { path = "../audio_zone", default-features = false }
moosicbox_core = { path = "../core", default-features = false }
moosicbox_database = { path = "../database", default-features = false, features = [
    "sqlite-sqlx",
] }
moosicbox_json_utils = { path = "../json_utils", default-features = false, features = [
    "database",
] }
moosicbox_logging = { path = "../logging", default-features = false }
moosicbox_session = { path = "../session", default-features = false }

actix-cors                   = { workspace = true, optional = true }
actix-files                  = { workspace = true, optional = true }
actix-rt                     = { workspace = true, optional = true }
actix-web                    = { workspace = true, optional = true }
async-once-cell              = { workspace = true, optional = true }
async-trait                  = { workspace = true, optional = true }
awc                          = { workspace = true, optional = true }
aws-config                   = { workspace = true, optional = true }
aws-sdk-apigatewaymanagement = { workspace = true, optional = true }
env_logger                   = { workspace = true, optional = true }
log                          = { workspace = true, optional = true }
once_cell                    = { workspace = true, optional = true }
regex                        = { workspace = true, optional = true }
thiserror                    = { workspace = true, optional = true }

serde        = { workspace = true, features = ["derive"] }
serde_json   = { workspace = true }
strum        = { workspace = true }
strum_macros = { workspace = true }

rusqlite = { workspace = true }

[features]
default = ["aac", "flac", "mp3", "opus", "ws"]

fail-on-warnings = []

ws = [
    "dep:actix-cors",
    "dep:actix-files",
    "dep:actix-rt",
    "dep:actix-web",
    "dep:async-once-cell",
    "dep:async-trait",
    "dep:awc",
    "dep:aws-config",
    "dep:aws-sdk-apigatewaymanagement",
    "dep:env_logger",
    "dep:log",
    "dep:once_cell",
    "dep:regex",
    "dep:thiserror",
]

aac  = ["moosicbox_session/aac"]
flac = ["moosicbox_session/flac"]
mp3  = ["moosicbox_session/mp3"]
opus = ["moosicbox_session/opus"]
