[package]
name = "moosicbox_ws"
version = "0.1.0"
authors = ["Braden Steffaniak"]
edition = "2021"

[dependencies]
actix-cors = "0.6.4"
actix-files = "0.6.2"
actix-rt = "2.9.0"
actix-web = "4.4.0"
async-once-cell = "0.5.3"
async-trait.workspace = true
awc = "3.0.0-beta.9"
aws-config = "0.56.1"
aws-sdk-apigatewaymanagement = "0.32.0"
aws_lambda_events = "0.11.1"
env_logger.workspace = true
lambda_runtime = "0.8.2"
log = { workspace = true }
moosicbox_core = { path = "../core" }
regex = "1.9.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.107"
thiserror = "1.0.48"

rusqlite = { workspace = true }

[features]
fail-on-warnings = []
