[package]
authors     = ["Braden Steffaniak"]
categories  = ["network-programming"]
description = "MoosicBox websocket package"
edition     = "2021"
keywords    = ["api", "websocket"]
license     = "MPL-2.0"
name        = "moosicbox_ws"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBoxServer"
version     = "0.1.0"

[package.metadata.cargo-machete]
ignored = ["strum"]

[dependencies]
moosicbox_assert = { path = "../assert", default-features = false }
moosicbox_audio_zone = { path = "../audio_zone", default-features = false }
moosicbox_core = { path = "../core", default-features = false }
moosicbox_database = { path = "../database", default-features = false }
moosicbox_json_utils = { path = "../json_utils", default-features = false, features = [
    "database",
] }
moosicbox_logging = { path = "../logging", default-features = false }
moosicbox_session = { path = "../session", default-features = false }

async-trait = { workspace = true, optional = true }
log         = { workspace = true, optional = true }
thiserror   = { workspace = true, optional = true }

serde        = { workspace = true, features = ["derive"] }
serde_json   = { workspace = true }
strum        = { workspace = true }
strum_macros = { workspace = true }

[features]
default = ["aac", "flac", "mp3", "opus", "ws"]

fail-on-warnings = []

ws = [
    "dep:async-trait",
    "dep:log",
    "dep:thiserror",
]

aac  = ["moosicbox_session/aac"]
flac = ["moosicbox_session/flac"]
mp3  = ["moosicbox_session/mp3"]
opus = ["moosicbox_session/opus"]
