[package]
authors     = ["Braden Steffaniak"]
categories  = ["network-programming"]
description = "MoosicBox websocket package"
edition     = "2021"
keywords    = ["api", "websocket"]
license     = "MPL-2.0"
name        = "moosicbox_ws"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBoxServer"
version     = "0.1.0"

[dependencies]
moosicbox_core = { path = "../core", default-features = false }
moosicbox_database = { path = "../database", default-features = false, features = [
    "rusqlite",
] }

actix-cors                   = { workspace = true }
actix-files                  = { workspace = true }
actix-rt                     = { workspace = true }
actix-web                    = { workspace = true }
async-once-cell              = { workspace = true }
awc                          = { workspace = true }
aws-config                   = { workspace = true }
aws-sdk-apigatewaymanagement = { workspace = true }
env_logger                   = { workspace = true }
log                          = { workspace = true }
once_cell                    = { workspace = true }
regex                        = { workspace = true }
serde                        = { workspace = true, features = ["derive"] }
serde_json                   = { workspace = true }
strum                        = { workspace = true }
strum_macros                 = { workspace = true }
thiserror                    = { workspace = true }

rusqlite = { workspace = true }

[features]
default = []

fail-on-warnings = []
