[package]
name = "moosicbox_player"
version = "0.1.0"
authors = ["Braden Steffaniak"]
edition = "2021"

[dependencies]
actix-cors = "0.6.4"
actix-files = "0.6.2"
actix-web = "4.4.0"
awc = "3.0.0-beta.9"
lambda-web = { version = "0.2.1", features=["actix4"] }
lambda_runtime = "0.8.2"
lazy_static = { workspace = true }
moosicbox_core = { path = "../core" }
moosicbox_symphonia_player = { path = "../../players/symphonia_player" }
rand.workspace = true
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.107"
thiserror = "1.0.48"
tokio = { workspace = true, features = ["rt", "time", "macros"] }

[features]
fail-on-warnings = []
