[package]
authors = ["Braden Steffaniak"]
edition = "2021"
name    = "moosicbox_player"
version = "0.1.0"

[dependencies]
moosicbox_converter        = { path = "../converter", default-features = false }
moosicbox_core             = { path = "../core", default-features = false }
moosicbox_symphonia_player = { path = "../../players/symphonia_player", default-features = false }

actix-cors        = { workspace = true }
actix-files       = { workspace = true }
actix-web         = { workspace = true }
atomic_float      = { workspace = true }
awc               = { workspace = true }
bytes             = { workspace = true }
crossbeam-channel = { workspace = true }
futures           = { workspace = true }
lazy_static       = { workspace = true }
log               = { workspace = true }
ogg               = { workspace = true }
once_cell         = { workspace = true }
rand              = { workspace = true }
reqwest           = { workspace = true, features = ["json"] }
serde             = { workspace = true, features = ["derive"] }
serde_json        = { workspace = true }
symphonia         = { workspace = true }
thiserror         = { workspace = true }
tokio             = { workspace = true, features = ["rt", "time", "macros"] }
tokio-util        = { workspace = true }
url               = { workspace = true }

[features]
default = ["cpal", "aac", "flac", "mp3", "opus", "pulseaudio"]

fail-on-warnings = []

# Player audio outputs
asio                = ["moosicbox_symphonia_player/asio"]
cpal                = ["moosicbox_symphonia_player/cpal"]
jack                = ["moosicbox_symphonia_player/jack"]
pulseaudio          = ["pulseaudio-standard", "pulseaudio-simple"]
pulseaudio-simple   = ["moosicbox_symphonia_player/pulseaudio-simple"]
pulseaudio-standard = ["moosicbox_symphonia_player/pulseaudio-standard"]
resampler           = ["moosicbox_symphonia_player/resampler"]

aac = [
    "moosicbox_symphonia_player/aac",
    "moosicbox_converter/aac",
    "moosicbox_core/aac",
]
flac = ["moosicbox_core/flac"]
mp3 = [
    "moosicbox_symphonia_player/mp3",
    "moosicbox_converter/mp3",
    "moosicbox_core/mp3",
]
opus = [
    "moosicbox_symphonia_player/opus",
    "moosicbox_converter/opus",
    "moosicbox_core/opus",
]
