[package]
authors     = ["Braden Steffaniak"]
categories  = ["development-tools", "multimedia"]
description = "MoosicBox player package"
edition     = "2021"
keywords    = ["audio", "player"]
license     = "MPL-2.0"
name        = "moosicbox_player"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBoxServer"
version     = "0.1.0"

[dependencies]
moosicbox_assert = { path = "../assert", default-features = false }
moosicbox_audio_decoder = { path = "../audio_decoder", default-features = false }
moosicbox_audio_output = { path = "../audio_output", default-features = false }
moosicbox_core = { path = "../core", default-features = false }
moosicbox_database = { path = "../database", default-features = false }
moosicbox_json_utils = { path = "../json_utils", default-features = false, features = [
    "serde_json",
] }
moosicbox_logging = { path = "../logging", default-features = false }
moosicbox_music_api = { path = "../music_api", default-features = false }
moosicbox_resampler = { path = "../resampler", default-features = false }
moosicbox_session = { path = "../session", default-features = false }
moosicbox_stream_utils = { path = "../stream_utils", default-features = false }
moosicbox_task = { path = "../task", default-features = false }

#API Dependencies
utoipa = { workspace = true, optional = true }

actix-web        = { workspace = true, optional = true }
async-trait      = { workspace = true }
atomic_float     = { workspace = true }
bytes            = { workspace = true }
flume            = { workspace = true }
futures          = { workspace = true }
local-ip-address = { workspace = true }
log              = { workspace = true }
rand             = { workspace = true }
regex            = { workspace = true }
reqwest          = { workspace = true, features = ["json"] }
serde            = { workspace = true, features = ["derive"] }
serde_json       = { workspace = true }
symphonia        = { workspace = true }
thiserror        = { workspace = true }
tokio            = { workspace = true, features = ["macros", "rt", "time", "tracing"] }
tokio-util       = { workspace = true }
url              = { workspace = true }

[features]
default = [
    "aac",
    "api",
    "cpal",
    "flac",
    "local",
    "mp3",
    "oboe-shared-stdcxx",
    "openapi",
    "opus",
    "pulseaudio",
]

fail-on-warnings = []

api     = ["dep:actix-web", "moosicbox_music_api/api"]
openapi = ["dep:utoipa"]

# Player audio outputs
asio                = ["moosicbox_audio_output/asio"]
cpal                = ["moosicbox_audio_output/cpal"]
jack                = ["moosicbox_audio_output/jack"]
oboe-shared-stdcxx  = ["moosicbox_audio_output/oboe-shared-stdcxx"]
pulseaudio          = ["pulseaudio-simple", "pulseaudio-standard"]
pulseaudio-simple   = ["moosicbox_audio_output/pulseaudio-simple"]
pulseaudio-standard = ["moosicbox_audio_output/pulseaudio-standard"]

aac = [
    "moosicbox_audio_output/aac",
    "moosicbox_core/aac",
    "moosicbox_session/aac",
]
flac = [
    "moosicbox_audio_output/flac",
    "moosicbox_core/flac",
    "moosicbox_session/flac",
]
mp3 = [
    "moosicbox_audio_output/mp3",
    "moosicbox_core/mp3",
    "moosicbox_session/mp3",
]
opus = [
    "moosicbox_audio_output/opus",
    "moosicbox_core/opus",
    "moosicbox_session/opus",
]

local = []
