[package]
authors     = ["Braden Steffaniak"]
categories  = ["development-tools", "multimedia"]
description = "MoosicBox player package"
edition     = "2021"
keywords    = ["audio", "player"]
license     = "MPL-2.0"
name        = "moosicbox_player"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBoxServer"
version     = "0.1.0"

[dependencies]
moosicbox_converter = { path = "../converter", default-features = false }
moosicbox_core = { path = "../core", default-features = false }
moosicbox_database = { path = "../database", default-features = false, features = [
    "rusqlite",
] }
moosicbox_json_utils = { path = "../json_utils", default-features = false, features = [
    "serde_json",
] }
moosicbox_stream_utils = { path = "../stream_utils", default-features = false }
moosicbox_symphonia_player = { path = "../symphonia_player", default-features = false }

actix-cors        = { workspace = true }
actix-files       = { workspace = true }
actix-web         = { workspace = true }
atomic_float      = { workspace = true }
awc               = { workspace = true }
bytes             = { workspace = true }
crossbeam-channel = { workspace = true }
futures           = { workspace = true }
lazy_static       = { workspace = true }
log               = { workspace = true }
ogg               = { workspace = true }
once_cell         = { workspace = true }
rand              = { workspace = true }
reqwest           = { workspace = true, features = ["json"] }
serde             = { workspace = true, features = ["derive"] }
serde_json        = { workspace = true }
symphonia         = { workspace = true }
thiserror         = { workspace = true }
tokio             = { workspace = true, features = ["macros", "rt", "time"] }
tokio-util        = { workspace = true }
url               = { workspace = true }

[features]
default = [
    "aac",
    "cpal",
    "flac",
    "mp3",
    "oboe-shared-stdcxx",
    "opus",
    "pulseaudio",
]

fail-on-warnings = []

# Player audio outputs
asio                = ["moosicbox_symphonia_player/asio"]
cpal                = ["moosicbox_symphonia_player/cpal"]
jack                = ["moosicbox_symphonia_player/jack"]
oboe-shared-stdcxx  = ["moosicbox_symphonia_player/oboe-shared-stdcxx"]
pulseaudio          = ["pulseaudio-simple", "pulseaudio-standard"]
pulseaudio-simple   = ["moosicbox_symphonia_player/pulseaudio-simple"]
pulseaudio-standard = ["moosicbox_symphonia_player/pulseaudio-standard"]
resampler           = ["moosicbox_symphonia_player/resampler"]

aac = [
    "moosicbox_converter/aac",
    "moosicbox_core/aac",
    "moosicbox_symphonia_player/aac",
]
flac = ["moosicbox_core/flac"]
mp3 = [
    "moosicbox_converter/mp3",
    "moosicbox_core/mp3",
    "moosicbox_symphonia_player/mp3",
]
opus = [
    "moosicbox_converter/opus",
    "moosicbox_core/opus",
    "moosicbox_symphonia_player/opus",
]
