[package]
authors     = ["Braden Steffaniak"]
categories  = ["development-tools"]
description = "MoosicBox assert package"
edition     = "2021"
keywords    = ["assert", "false", "true", "util", "utils"]
license     = "MPL-2.0"
name        = "moosicbox_assert"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBox"
version     = "0.1.0"

[dependencies]
moosicbox_env_utils = { version = "0.1.0", path = "../env_utils", default-features = false }

colored = { version = "2.2.0" }

[features]
fail-on-warnings = []
