[package]
name = "moosicbox_server"
version = "0.1.0"
authors = ["Braden Steffaniak"]
edition = "2021"

[dependencies]
actix = "0.13.1"
actix-cors = "0.6.4"
actix-files = "0.6.2"
actix-web = "4.4.0"
actix-web-actors = "4.2.0"
audiotags = { path = "../../audiotags" }
awc = "3.0.0-beta.9"
enum-as-inner = "0.6.0"
futures = "0.3"
moosicbox_core = { path = "../packages/core" }
moosicbox_menu = { path = "../packages/menu" }
moosicbox_files = { path = "../packages/files" }
moosicbox_ws = { path = "../packages/ws" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.105"
sqlite = "0.31.1"
thiserror = "1.0.48"
regex = "1.9.5"
mp3-duration = "0.1.10"
uuid = { version = "1.4.1", features = ["v4"] }

[features]
fail-on-warnings = []
