[package]
authors     = ["Braden Steffaniak"]
categories  = ["network-programming"]
description = "MoosicBox UPnP package"
edition     = "2021"
keywords    = ["dlna", "network", "upnp"]
license     = "MPL-2.0"
name        = "moosicbox_upnp"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBoxServer"
version     = "0.1.0"

[dependencies]
moosicbox_assert = { path = "../assert", default-features = false }

# API Dependencies
actix-web = { workspace = true, optional = true }

# Listener Dependencies
flume                   = { workspace = true, optional = true }
moosicbox_async_service = { path = "../async_service", optional = true }
tokio-util              = { workspace = true, optional = true }

# Player Dependencies
async-trait = { workspace = true, optional = true }
atomic_float = { workspace = true, optional = true }
crossbeam-channel = { workspace = true, optional = true }
moosicbox_core = { path = "../core", optional = true }
moosicbox_database = { path = "../database", optional = true }
moosicbox_json_utils = { path = "../json_utils", optional = true }
moosicbox_player = { path = "../player", optional = true }
moosicbox_stream_utils = { path = "../stream_utils", optional = true, features = [
    "remote-bytestream",
] }
moosicbox_symphonia_player = { path = "../symphonia_player", optional = true }
rand = { workspace = true, optional = true }
reqwest = { workspace = true, optional = true }
symphonia = { workspace = true, optional = true }
url = { workspace = true, optional = true }

async-recursion = { workspace = true }
futures         = { workspace = true }
log             = { workspace = true }
once_cell       = { workspace = true }
pin-utils       = { workspace = true }
regex           = { workspace = true }
rupnp           = { workspace = true }
serde           = { workspace = true }
serde_json      = { workspace = true }
strum           = { workspace = true }
strum_macros    = { workspace = true }
thiserror       = { workspace = true }
tokio           = { workspace = true, optional = true, features = ["macros"] }
xml             = { workspace = true }

[features]
default = ["api", "listener", "player"]

fail-on-warnings = []


api = ["dep:actix-web", "dep:tokio"]
listener = ["dep:flume", "dep:tokio", "dep:tokio-util"]
player = [
    "dep:async-trait",
    "dep:atomic_float",
    "dep:crossbeam-channel",
    "dep:moosicbox_async_service",
    "dep:moosicbox_core",
    "dep:moosicbox_database",
    "dep:moosicbox_json_utils",
    "dep:moosicbox_player",
    "dep:moosicbox_stream_utils",
    "dep:moosicbox_symphonia_player",
    "dep:rand",
    "dep:reqwest",
    "dep:symphonia",
    "dep:url",
    "listener",
]
