[package]
authors     = ["Braden Steffaniak"]
categories  = ["network-programming"]
description = "MoosicBox UPnP package"
edition     = "2021"
keywords    = ["dlna", "network", "upnp"]
license     = "MPL-2.0"
name        = "moosicbox_upnp"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBox"
version     = "0.1.0"

[package.metadata.cargo-machete]
ignored = ["strum"]

[dependencies]
moosicbox_assert       = { path = "../assert", default-features = false }
moosicbox_audio_output = { path = "../audio_output", optional = true, default-features = false }
moosicbox_logging      = { path = "../logging", optional = true, default-features = false }
moosicbox_task         = { path = "../task", default-features = false }

# API Dependencies
actix-web = { workspace = true, optional = true }
utoipa    = { workspace = true, optional = true }

# Listener Dependencies
flume                   = { workspace = true, optional = true }
moosicbox_async_service = { path = "../async_service", optional = true }
tokio-util              = { workspace = true, optional = true }

# Player Dependencies
async-trait         = { workspace = true, optional = true }
moosicbox_core      = { path = "../core", default-features = false, optional = true }
moosicbox_music_api = { path = "../music_api", default-features = false, optional = true }
moosicbox_player    = { path = "../player", default-features = false, optional = true }
moosicbox_session   = { path = "../session", default-features = false, optional = true }
rand                = { workspace = true, optional = true }
reqwest             = { workspace = true, optional = true }
symphonia           = { workspace = true, optional = true }

async-recursion = { workspace = true }
futures         = { workspace = true }
itertools       = { workspace = true }
log             = { workspace = true }
pin-utils       = { workspace = true }
regex           = { workspace = true }
roxmltree       = { workspace = true }
rupnp           = { workspace = true }
serde           = { workspace = true }
strum           = { workspace = true, optional = true }
strum_macros    = { workspace = true, optional = true }
thiserror       = { workspace = true }
tokio           = { workspace = true, features = ["macros", "tracing"] }
xml             = { workspace = true }

[features]
default = ["api", "listener", "openapi", "player"]

fail-on-warnings = []

api = ["dep:actix-web"]
listener = ["dep:flume", "dep:tokio-util"]
openapi = ["dep:utoipa"]
player = [
    "dep:async-trait",
    "dep:moosicbox_async_service",
    "dep:moosicbox_audio_output",
    "dep:moosicbox_core",
    "dep:moosicbox_logging",
    "dep:moosicbox_music_api",
    "dep:moosicbox_player",
    "dep:moosicbox_session",
    "dep:rand",
    "dep:reqwest",
    "dep:strum",
    "dep:strum_macros",
    "dep:symphonia",
    "listener",
]
