[[config]]
os = "ubuntu"

[[config.dependencies]]
command  = "sudo apt-get update && sudo apt-get install libasound2-dev"
features = ["default", "player"]

[[config.dependencies]]
command  = "sudo apt-get update && sudo apt-get install pulseaudio"
features = ["default", "player"]
