[package]
authors     = ["Braden Steffaniak"]
build       = "build.rs"
categories  = ["gui"]
description = "HyperChad Vanilla JS HTML renderer package"
edition     = "2021"
keywords    = ["gui", "html", "js", "render", "web"]
license     = "MPL-2.0"
name        = "hyperchad_renderer_vanilla_js"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBox"
version     = "0.1.0"

[package.metadata.cargo-machete]
ignored = ["hyperchad_js_bundler"]

[build-dependencies]
hyperchad_js_bundler = { version = "0.1.0", path = "../../js_bundler", default-features = false, features = [
    "default",
] }

[dependencies]
hyperchad_renderer = { version = "0.1.0", path = "..", default-features = false, features = [
    "canvas",
    "html",
] }
hyperchad_renderer_html = { version = "0.1.0", path = "../html", default-features = false, features = [
    "assets",
    "extend",
] }
hyperchad_transformer = { version = "0.1.0", path = "../../transformer", default-features = false, features = [
    "html",
] }

async-trait  = { workspace = true }
const_format = { workspace = true }
log          = { workspace = true }
maud         = { workspace = true }
md5          = { workspace = true, optional = true }

[features]
default = ["debug", "esbuild", "swc"]

fail-on-warnings = []

debug = []

hash   = ["dep:md5"]
script = []

esbuild = []
swc     = []
