[package]
authors     = ["Braden Steffaniak"]
categories  = ["development-tools", "gui", "web-programming"]
description = "MoosicBox Giga-Chad Router package"
edition     = "2021"
keywords    = ["dom", "gigachad", "router", "web"]
license     = "MPL-2.0"
name        = "gigachad_router"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBox"
version     = "0.1.0"

[dependencies]
gigachad_transformer = { version = "0.1.0", path = "../transformer", default-features = false, features = [
    "html",
] }
moosicbox_assert = { version = "0.1.0", path = "../../assert", default-features = false }
moosicbox_task = { version = "0.1.0", path = "../../task", default-features = false }

flume     = { workspace = true }
futures   = { workspace = true }
log       = { workspace = true }
qstring   = { workspace = true }
thiserror = { workspace = true }
tokio     = { workspace = true, features = ["rt-multi-thread", "sync"] }

[features]
default = ["format", "id"]

fail-on-warnings = []

simd = ["gigachad_transformer/simd"]

format = ["gigachad_transformer/format"]

id = []
