[package]
authors     = ["Braden Steffaniak"]
categories  = ["compression", "encoding"]
description = "Audio converter helper binary"
edition     = "2021"
keywords    = ["audio", "convert", "converter", "encoding"]
license     = "MPL-2.0"
name        = "moosicbox_aconverter"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBoxServer"
version     = "0.1.0"

[[bin]]
name              = "aconverter"
path              = "src/main.rs"
required-features = []

[dependencies]
moosicbox_assert = { path = "../assert", default-features = false }
moosicbox_core = { path = "../core", default-features = false }
moosicbox_files = { path = "../files", default-features = false, features = [
    "files",
] }
moosicbox_logging = { path = "../logging", default-features = false }
moosicbox_music_api = { path = "../music_api", default-features = false }

audiotags = { workspace = true }
clap = { workspace = true }
futures = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = [
    "macros",
    "rt-multi-thread",
    "tracing",
] }

[features]
default = ["aac", "flac", "mp3", "opus"]

fail-on-warnings = []

aac  = ["moosicbox_files/aac"]
flac = ["moosicbox_files/flac"]
mp3  = ["moosicbox_files/mp3"]
opus = ["moosicbox_files/opus"]
