[package]
authors     = ["Braden Steffaniak"]
categories  = ["multimedia", "network-programming"]
description = "MoosicBox YouTube package"
edition     = "2021"
keywords    = ["audio", "youtube"]
license     = "MPL-2.0"
name        = "moosicbox_yt"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBox"
version     = "0.1.0"

[package.metadata.cargo-machete]
ignored = ["strum"]

[dependencies]
moosicbox_assert = { version = "0.1.0", path = "../assert", default-features = false }
moosicbox_core = { version = "0.1.0", path = "../core", default-features = false }
moosicbox_database = { version = "0.1.0", path = "../database", default-features = false }
moosicbox_files = { version = "0.1.0", path = "../files", default-features = false }
moosicbox_json_utils = { version = "0.1.0", path = "../json_utils", default-features = false, features = [
    "database",
    "serde_json",
] }
moosicbox_music_api = { version = "0.1.0", path = "../music_api", default-features = false }
moosicbox_paging = { version = "0.1.0", path = "../paging", default-features = false }
moosicbox_search = { version = "0.1.0", path = "../search", default-features = false }

# API Dependencies
actix-web = { workspace = true, optional = true }
utoipa    = { workspace = true, optional = true }

async-recursion = { workspace = true }
async-trait     = { workspace = true }
chrono          = { workspace = true }
futures         = { workspace = true }
log             = { workspace = true }
open            = { workspace = true }
reqwest         = { workspace = true, features = ["json"] }
serde           = { workspace = true, features = ["derive"] }
serde_json      = { workspace = true }
strum           = { workspace = true }
strum_macros    = { workspace = true }
thiserror       = { workspace = true }
tokio           = { workspace = true, features = ["macros", "tracing"] }
url             = { workspace = true }

[features]
default = ["api", "db", "openapi"]

fail-on-warnings = []

api     = ["dep:actix-web", "moosicbox_database/api", "moosicbox_database/api"]
db      = ["moosicbox_music_api/db"]
openapi = ["dep:utoipa", "moosicbox_search/openapi"]
