[package]
authors     = ["Braden Steffaniak"]
categories  = ["gui"]
description = "Giga-Chad htmx renderer package"
edition     = "2021"
keywords    = ["gui", "htmx", "render", "renderer", "web"]
license     = "MPL-2.0"
name        = "gigachad_renderer_htmx"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBox"
version     = "0.1.0"

[package.metadata.cargo-machete]
ignored = ["image"]

[dependencies]
gigachad_renderer = { version = "0.1.0", path = "../", default-features = false, features = [
    "viewport-immediate",
] }
gigachad_router = { version = "0.1.0", path = "../../../gigachad/router", default-features = false }
gigachad_transformer = { version = "0.1.0", path = "../../transformer", default-features = false, features = [
    "calc",
    "html",
    "id",
] }
moosicbox_app_native_image = { version = "0.1.0", path = "../../../app/native/image", default-features = false }
moosicbox_assert = { version = "0.1.0", path = "../../../assert", default-features = false }
moosicbox_env_utils = { version = "0.1.0", path = "../../../env_utils", default-features = false }
moosicbox_logging = { version = "0.1.0", path = "../../../logging", default-features = false, features = [
    "macros",
] }
moosicbox_middleware = { version = "0.1.0", path = "../../../middleware", default-features = false }
moosicbox_task = { version = "0.1.0", path = "../../../task", default-features = false }

actix-cors  = { workspace = true }
actix-htmx  = { workspace = true }
actix-web   = { workspace = true }
async-trait = { workspace = true }
flume       = { workspace = true }
log         = { workspace = true }
tokio       = { workspace = true }

[features]
default = ["debug"]

fail-on-warnings = []

debug = []
