[package]
authors     = ["Braden Steffaniak"]
categories  = ["multimedia"]
description = "MoosicBox files package"
edition     = "2021"
keywords    = ["audio", "file", "track"]
license     = "MPL-2.0"
name        = "moosicbox_files"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBoxServer"
version     = "0.1.0"

[dependencies]
moosicbox_assert = { path = "../assert", default-features = false }
moosicbox_async_service = { path = "../async_service", default-features = false }
moosicbox_config = { path = "../config", default-features = false }
moosicbox_core = { path = "../core", default-features = false }
moosicbox_database = { path = "../database", default-features = false, features = [
    "rusqlite",
] }
moosicbox_image = { path = "../image", default-features = false }
moosicbox_json_utils = { path = "../json_utils", default-features = false, features = [
    "rusqlite",
    "serde_json",
] }
moosicbox_music_api = { path = "../music_api", default-features = false }
moosicbox_stream_utils = { path = "../stream_utils", default-features = false }
moosicbox_audio_decoder = { path = "../audio_decoder", default-features = false }
moosicbox_task = { path = "../task", default-features = false }

# API Dependencies
utoipa = { workspace = true, optional = true }

actix-cors      = { workspace = true }
actix-files     = { workspace = true }
actix-web       = { workspace = true }
async-recursion = { workspace = true }
atomic_float    = { workspace = true }
audiotags       = { workspace = true }
awc             = { workspace = true }
bytes           = { workspace = true }
flume           = { workspace = true }
futures         = { workspace = true }
futures-core    = { workspace = true }
lazy_static     = { workspace = true }
log             = { workspace = true }
once_cell       = { workspace = true }
regex           = { workspace = true }
reqwest         = { workspace = true }
rusqlite        = { workspace = true }
serde           = { workspace = true, features = ["derive"] }
serde_json      = { workspace = true }
strum           = { workspace = true }
strum_macros    = { workspace = true }
symphonia       = { workspace = true }
thiserror       = { workspace = true }
tokio           = { workspace = true }
tokio-stream    = { workspace = true }
tokio-util      = { workspace = true }

[features]
default = [
    "aac",
    "api",
    "files",
    "flac",
    "image",
    "mp3",
    "openapi",
    "opus",
    "range",
]

fail-on-warnings = []

image   = ["moosicbox_image/image"]
libvips = ["moosicbox_image/libvips"]

api         = ["files", "range"]
files       = []
openapi     = ["dep:utoipa", "moosicbox_core/openapi"]
range       = []
track-range = []

aac  = ["moosicbox_core/aac", "moosicbox_audio_decoder/aac"]
flac = ["moosicbox_core/flac", "moosicbox_audio_decoder/flac"]
mp3  = ["moosicbox_core/mp3", "moosicbox_audio_decoder/mp3"]
opus = ["moosicbox_core/opus", "moosicbox_audio_decoder/opus"]
