[package]
authors = ["Braden Steffaniak"]
edition = "2021"
name    = "moosicbox_files"
version = "0.1.0"

[dependencies]
moosicbox_core             = { path = "../core" }
moosicbox_image            = { path = "../image", default-features = false }
moosicbox_stream_utils     = { path = "../stream_utils" }
moosicbox_symphonia_player = { path = "../../players/symphonia_player", default-features = false }
moosicbox_tidal            = { path = "../tidal" }

actix-cors   = { workspace = true }
actix-files  = { workspace = true }
actix-web    = { workspace = true }
awc          = { workspace = true }
bytes        = { workspace = true }
lazy_static  = { workspace = true }
log          = { workspace = true }
regex        = { workspace = true }
reqwest      = { workspace = true }
serde        = { workspace = true, features = ["derive"] }
serde_json   = { workspace = true }
strum        = { workspace = true }
strum_macros = { workspace = true }
symphonia    = { workspace = true }
thiserror    = { workspace = true }
tokio        = { workspace = true }
tokio-stream = { workspace = true }
tokio-util   = { workspace = true }

[features]
default = ["image", "aac", "flac", "mp3", "opus"]

fail-on-warnings = []

image   = ["moosicbox_image/image"]
libvips = ["moosicbox_image/libvips"]

aac  = ["moosicbox_symphonia_player/aac"]
flac = []
mp3  = ["moosicbox_symphonia_player/mp3"]
opus = ["moosicbox_symphonia_player/opus"]
