[package]
name = "moosicbox_files"
version = "0.1.0"
authors = ["Braden Steffaniak"]
edition = "2021"

[dependencies]
actix-cors = "0.6.4"
actix-files = "0.6.2"
actix-web = "4.4.0"
awc = "3.0.0-beta.9"
lambda-web = { version = "0.2.1", features=["actix4"] }
lambda_runtime = "0.8.2"
moosicbox_core = { path = "../core" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.107"
sqlite = "0.31.1"
thiserror = "1.0.48"
