[package]
authors = ["Braden Steffaniak"]
edition = "2021"
name    = "moosicbox_files"
version = "0.1.0"

[dependencies]
actix-cors      = "0.6.4"
actix-files     = "0.6.2"
actix-web       = "4.4.0"
awc             = "3.0.0-beta.9"
lambda-web      = { workspace = true }
lambda_runtime  = { workspace = true }
log             = { workspace = true }
moosicbox_core  = { path = "../core" }
moosicbox_image = { path = "../image", default-features = false }
regex           = "1.9.5"
serde           = { workspace = true, features = ["derive"] }
serde_json      = { workspace = true }
thiserror       = { workspace = true }

[features]
default = ["image"]

fail-on-warnings = []

image   = ["moosicbox_image/image"]
libvips = ["moosicbox_image/libvips"]
