[package]
name = "moosicbox_files"
version = "0.1.0"
authors = ["Braden Steffaniak"]
edition = "2021"

[dependencies]
actix-cors = "0.6.4"
actix-files = "0.6.2"
actix-web = "4.4.0"
awc = "3.0.0-beta.9"
lambda-web = { workspace = true }
lambda_runtime = { workspace = true }
log = { workspace = true }
moosicbox_core = { path = "../core" }
regex = "1.9.5"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = "1.0.48"

[features]
fail-on-warnings = []
