[package]
authors = ["Braden Steffaniak"]
edition = "2021"
name    = "moosicbox_json_utils"
version = "0.1.0"

[dependencies]
serde      = { workspace = true }
serde_json = { workspace = true }
thiserror  = { workspace = true }

[features]
fail-on-warnings = []
