[package]
authors = ["Braden Steffaniak"]
edition = "2021"
name    = "moosicbox_json_utils"
version = "0.1.0"

[dependencies]
# database dependencies
moosicbox_database = { path = "../database", optional = true, default-features = false, features = [
    "rusqlite",
] }

# rusqlite dependencies
rusqlite = { workspace = true, optional = true }

# tantivy dependencies
tantivy = { workspace = true, optional = true }

# serde_json dependencies
serde      = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }

log       = { workspace = true }
thiserror = { workspace = true }

[features]
default = ["database", "rusqlite", "serde_json", "tantivy"]

fail-on-warnings = []

database   = ["dep:moosicbox_database"]
rusqlite   = ["dep:rusqlite"]
serde_json = ["dep:serde", "dep:serde_json"]
tantivy    = ["dep:tantivy"]
