[package]
authors = ["Braden Steffaniak"]
edition = "2021"
name    = "moosicbox_json_utils"
version = "0.1.0"

[dependencies]
# rusqlite dependencies
rusqlite = { workspace = true, optional = true }

# tantivy dependencies
tantivy = { workspace = true, optional = true }

# serde_json dependencies
serde      = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }

thiserror = { workspace = true }

[features]
default = ["rusqlite", "serde_json", "tantivy"]

fail-on-warnings = []

rusqlite   = ["dep:rusqlite"]
serde_json = ["dep:serde", "dep:serde_json"]
tantivy    = ["dep:tantivy"]
