[package]
authors     = ["Braden Steffaniak"]
categories  = ["database", "development-tools"]
description = "MoosicBox json utilities package"
edition     = "2021"
keywords    = ["database", "json", "tantivy", "util", "utility"]
license     = "MPL-2.0"
name        = "moosicbox_json_utils"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBoxServer"
version     = "0.1.0"

[dependencies]
moosicbox_assert = { path = "../assert", default-features = false }

# database dependencies
moosicbox_database = { path = "../database", optional = true, default-features = false, features = [
    "sqlite-sqlx",
] }

# rusqlite dependencies
rusqlite = { workspace = true, optional = true }

# tantivy dependencies
tantivy = { workspace = true, optional = true }

# serde_json dependencies
serde      = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }

chrono    = { workspace = true }
log       = { workspace = true }
thiserror = { workspace = true }

[features]
default = ["database", "rusqlite", "serde_json", "tantivy"]

fail-on-warnings = []

database   = ["dep:moosicbox_database"]
rusqlite   = ["dep:rusqlite"]
serde_json = ["dep:serde", "dep:serde_json"]
tantivy    = ["dep:tantivy"]
