[package]
authors = ["Braden Steffaniak"]
categories = ["development-tools", "gui", "web-programming"]
description = "MoosicBox Giga-Chad Transformer package"
edition = "2021"
keywords = [
    "chad",
    "dom",
    "giga",
    "gigachad",
    "gui",
    "html",
    "htmx",
    "transformer",
    "web",
]
license = "MPL-2.0"
name = "moosicbox_giga_chad_transformer"
readme = "README.md"
repository = "https://github.com/MoosicBox/MoosicBoxServer"
version = "0.1.0"

[dependencies]
thiserror = { workspace = true }
tl        = { workspace = true, optional = true }

[features]
default = ["html"]

fail-on-warnings = []

html = ["dep:tl"]
simd = ["tl?/simd"]
