[build]
rustflags = ["--cfg", "tokio_unstable"]

[alias]
server                                     = "server:release"
"server:cpal"                              = "run --package moosicbox_server --release --no-default-features --features=cpal,aac,flac,mp3,opus,all-apis,openapi"
"server:debug"                             = "server:debug:cpal"
"server:debug-release"                     = "server:debug-release:cpal"
"server:debug-release:cpal"                = "run --package moosicbox_server --profile debug-release --no-default-features --features=cpal,aac,flac,mp3,opus,all-apis,openapi"
"server:debug-release:pulseaudio-simple"   = "run --package moosicbox_server --profile debug-release --no-default-features --features=pulseaudio-simple,aac,flac,mp3,opus,all-apis,openapi"
"server:debug-release:pulseaudio-standard" = "run --package moosicbox_server --profile debug-release --no-default-features --features=pulseaudio-standard,aac,flac,mp3,opus,all-apis,openapi"
"server:debug:cpal"                        = "run --package moosicbox_server --no-default-features --features=cpal,aac,flac,mp3,opus,all-apis,openapi"
"server:debug:pulseaudio-simple"           = "run --package moosicbox_server --no-default-features --features=pulseaudio-simple,aac,flac,mp3,opus,all-apis,openapi"
"server:debug:pulseaudio-standard"         = "run --package moosicbox_server --no-default-features --features=pulseaudio-standard,aac,flac,mp3,opus,all-apis,openapi"
"server:pulseaudio-simple"                 = "run --package moosicbox_server --release --no-default-features --features=pulseaudio-simple,aac,flac,mp3,opus,all-apis,openapi"
"server:pulseaudio-standard"               = "run --package moosicbox_server --release --no-default-features --features=pulseaudio-standard,aac,flac,mp3,opus,all-apis,openapi"
"server:release"                           = "server:cpal"
"server:tls"                               = "server:tls:release"
"server:tls:cpal"                          = "run --package moosicbox_server --release --no-default-features --features=cpal,aac,flac,mp3,opus,all-apis,openapi,tls"
"server:tls:debug"                         = "server:tls:debug:cpal"
"server:tls:debug:cpal"                    = "run --package moosicbox_server --no-default-features --features=cpal,aac,flac,mp3,opus,all-apis,openapi,tls"
"server:tls:release"                       = "server:tls:cpal"

tunnel-server                      = "tunnel-server:release"
"tunnel-server:debug"              = "run --package moosicbox_tunnel_server --no-default-features --features=postgres-raw"
"tunnel-server:debug-release"      = "run --package moosicbox_tunnel_server --no-default-features --features=postgres-raw --profile debug-release"
"tunnel-server:debug-release:sqlx" = "run --package moosicbox_tunnel_server --no-default-features --features=postgres-sqlx --profile debug-release"
"tunnel-server:debug:sqlx"         = "run --package moosicbox_tunnel_server --no-default-features --features=postgres-sqlx"
"tunnel-server:release"            = "run --package moosicbox_tunnel_server --no-default-features --features=postgres-raw --release"
"tunnel-server:release:sqlx"       = "run --package moosicbox_tunnel_server --no-default-features --features=postgres-sqlx --release"
"tunnel-server:sqlx"               = "tunnel-server:release:sqlx"

[env]
RUST_LOG = "info"

[http]
timeout = 1000000

[net]
git-fetch-with-cli = true
