[package]
authors     = ["Braden Steffaniak"]
categories  = ["gui", "web-programming"]
description = "MoosicBox App UI package"
edition     = "2021"
keywords    = ["dom", "gui", "transformer", "web"]
license     = "MPL-2.0"
name        = "moosicbox_app_native_ui"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBox"
version     = "0.1.0"

[dependencies]
gigachad_actions = { version = "0.1.0", path = "../../../gigachad/actions", default-features = false, features = [
    "logic",
    "serde",
] }
gigachad_transformer_models = { version = "0.1.0", path = "../../../gigachad/transformer/models", default-features = false, features = [
    "serde",
] }
moosicbox_app_native_image = { version = "0.1.0", path = "../image", default-features = false }
moosicbox_core = { version = "0.1.0", path = "../../../core", default-features = false }
moosicbox_menu_models = { version = "0.1.0", path = "../../../menu/models", default-features = false, features = [
    "api",
] }
moosicbox_paging = { version = "0.1.0", path = "../../../paging", default-features = false }
moosicbox_session_models = { version = "0.1.0", path = "../../../session/models", default-features = false }

log        = { workspace = true }
maud       = { workspace = true }
serde      = { workspace = true }
serde_json = { workspace = true }

[features]
default = ["all-sources"]

fail-on-warnings = []

all-sources = ["qobuz", "tidal", "yt"]

qobuz = [
    "moosicbox_core/qobuz",
    "moosicbox_menu_models/qobuz",
    "moosicbox_session_models/qobuz",
]
tidal = [
    "moosicbox_core/tidal",
    "moosicbox_menu_models/tidal",
    "moosicbox_session_models/tidal",
]
yt = [
    "moosicbox_core/yt",
    "moosicbox_menu_models/yt",
    "moosicbox_session_models/yt",
]
