[package]
authors     = ["Braden Steffaniak"]
categories  = ["gui", "web-programming"]
description = "MoosicBox App UI package"
edition     = "2021"
keywords    = ["dom", "gui", "html", "htmx", "transformer", "web"]
license     = "MPL-2.0"
name        = "moosicbox_app_native_ui"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBox"
version     = "0.1.0"

[dependencies]
moosicbox_library_models = { version = "0.1.0", path = "../../../library/models", default-features = false }

maud = { workspace = true }

[features]
default = []

fail-on-warnings = []
