[package]
authors     = ["Braden Steffaniak"]
categories  = ["gui", "web-programming"]
description = "MoosicBox App UI package"
edition     = "2021"
keywords    = ["dom", "gui", "transformer", "web"]
license     = "MPL-2.0"
name        = "moosicbox_app_native_ui"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBox"
version     = "0.1.0"

[dependencies]
moosicbox_app_native_image = { version = "0.1.0", path = "../image", default-features = false }
moosicbox_core = { version = "0.1.0", path = "../../../core", default-features = false }
moosicbox_library_models = { version = "0.1.0", path = "../../../library/models", default-features = false }
moosicbox_menu_models = { version = "0.1.0", path = "../../../menu/models", default-features = false, features = [
    "api",
] }
moosicbox_paging = { version = "0.1.0", path = "../../../paging", default-features = false }
moosicbox_session_models = { version = "0.1.0", path = "../../../session/models", default-features = false }

log        = { workspace = true }
maud       = { workspace = true }
serde      = { workspace = true }
serde_json = { workspace = true }

[features]
default = []

fail-on-warnings = []
