[package]
authors     = ["Braden Steffaniak"]
categories  = ["gui"]
description = "MoosicBox fltk renderer package"
edition     = "2021"
keywords    = ["desktop", "gui", "render", "renderer"]
license     = "MPL-2.0"
name        = "moosicbox_app_native_renderer"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBox"
version     = "0.1.0"

[dependencies]
gigachad_transformer = { version = "0.1.0", path = "../../../gigachad/transformer", default-features = false, features = [
    "calc",
    "html",
] }
moosicbox_assert = { version = "0.1.0", path = "../../../assert", default-features = false }
moosicbox_task = { version = "0.1.0", path = "../../../task", default-features = false }

fltk      = { workspace = true, features = ["use-ninja"] }
flume     = { workspace = true }
futures   = { workspace = true }
image     = { workspace = true }
log       = { workspace = true }
reqwest   = { workspace = true }
thiserror = { workspace = true }
tokio     = { workspace = true, features = ["sync"] }

[features]
default = ["unsafe"]

fail-on-warnings = []

debug  = []
unsafe = []
