[package]
authors     = ["Braden Steffaniak"]
categories  = ["multimedia"]
description = "MoosicBox core package"
edition     = "2021"
keywords    = ["core"]
license     = "MPL-2.0"
name        = "moosicbox_core"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBoxServer"
version     = "0.1.0"

[dependencies]
moosicbox_assert = { path = "../assert", default-features = false }
moosicbox_database = { path = "../database", default-features = false, features = [
    "rusqlite",
] }
moosicbox_json_utils = { path = "../json_utils", default-features = false, features = [
    "database",
    "rusqlite",
    "serde_json",
] }

actix-cors    = { workspace = true }
actix-web     = { workspace = true }
async-trait   = { workspace = true }
awc           = { workspace = true }
enum-as-inner = { workspace = true }
futures       = { workspace = true }
log           = { workspace = true }
once_cell     = { workspace = true }
rusqlite      = { workspace = true }
serde         = { workspace = true, features = ["derive", "rc"] }
serde_json    = { workspace = true }
strum         = { workspace = true }
strum_macros  = { workspace = true }
tantivy       = { workspace = true, optional = true }
thiserror     = { workspace = true }

[features]
default = ["aac", "flac", "mp3", "opus", "tantivy"]

fail-on-warnings = []

aac  = []
flac = []
mp3  = []
opus = []

tantivy = ["dep:tantivy"]
