[package]
name = "moosicbox_core"
version = "0.1.0"
authors = ["Braden Steffaniak"]
edition = "2021"

[dependencies]
actix-cors = "0.6.4"
actix-web = "4"
awc = "3.0.0-beta.9"
enum-as-inner = "0.6.0"
futures = "0.3"
log = { workspace = true }
rusqlite = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.105"
strum = { workspace = true }
strum_macros = { workspace = true }
thiserror = "1.0.48"

[features]
fail-on-warnings = []
