[package]
authors = ["Braden Steffaniak"]
edition = "2021"
name    = "moosicbox_core"
version = "0.1.0"

[dependencies]
moosicbox_database = { path = "../database", default-features = false, features = [
    "rusqlite",
] }
moosicbox_json_utils = { path = "../json_utils", default-features = false, features = [
    "rusqlite",
    "serde_json",
    "database",
] }

actix-cors    = { workspace = true }
actix-web     = { workspace = true }
async-trait   = { workspace = true }
awc           = { workspace = true }
enum-as-inner = { workspace = true }
futures       = { workspace = true }
log           = { workspace = true }
once_cell     = { workspace = true }
rusqlite      = { workspace = true }
serde         = { workspace = true, features = ["derive"] }
serde_json    = { workspace = true }
strum         = { workspace = true }
strum_macros  = { workspace = true }
thiserror     = { workspace = true }

[features]
default = ["aac", "flac", "mp3", "opus"]

fail-on-warnings = []

aac  = []
flac = []
mp3  = []
opus = []
