[package]
authors     = ["Braden Steffaniak"]
categories  = ["development-tools", "network-programming"]
description = "MoosicBox stream utils package"
edition     = "2021"
keywords    = ["bytes", "stream", "util", "utility"]
license     = "MPL-2.0"
name        = "moosicbox_stream_utils"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBoxServer"
version     = "0.1.0"

[dependencies]
moosicbox_assert = { path = "../assert", default-features = false }
moosicbox_task   = { path = "../task", default-features = false }

bytes = { workspace = true }
flume = { workspace = true }
futures = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }
pin-project = { workspace = true }
reqwest = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = [
    "macros",
    "rt-multi-thread",
    "time",
    "tracing",
] }
tokio-util = { workspace = true }

[features]
default = ["remote-bytestream", "stalled-monitor"]

fail-on-warnings = []

remote-bytestream = []
stalled-monitor   = []
