[package]
authors     = ["Braden Steffaniak"]
categories  = ["gui"]
description = "GigaChad Datastar renderer package"
edition     = "2021"
keywords    = ["datastar", "gui", "render", "renderer", "web"]
license     = "MPL-2.0"
name        = "gigachad_renderer_datastar"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBox"
version     = "0.1.0"

[package.metadata.cargo-machete]
ignored = ["image"]

[dependencies]
gigachad_renderer = { version = "0.1.0", path = "..", default-features = false, features = [
    "canvas",
    "html",
] }
gigachad_renderer_html = { version = "0.1.0", path = "../html", default-features = false, features = [
    "assets",
] }
gigachad_router = { version = "0.1.0", path = "../../../gigachad/router", default-features = false }

log = { workspace = true }

[features]
default = ["debug"]

fail-on-warnings = []

debug = []
