[package]
authors     = ["Braden Steffaniak"]
categories  = ["multimedia"]
description = "MoosicBox server package"
edition     = "2021"
keywords    = ["api", "audio", "moosicbox", "server"]
license     = "MPL-2.0"
name        = "moosicbox_server"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBoxServer"
version     = "0.1.0"

[dependencies]
moosicbox_assert = { path = "../assert" }
moosicbox_auth = { path = "../auth" }
moosicbox_config = { path = "../config", default-features = false }
moosicbox_core = { path = "../core", default-features = false }
moosicbox_database = { path = "../database", default-features = false, features = [
    "rusqlite",
] }
moosicbox_downloader = { path = "../downloader", default-features = false, features = [
    "api",
] }
moosicbox_env_utils = { path = "../env_utils" }
moosicbox_files = { path = "../files", default-features = false, features = [
    "api",
    "files",
    "image",
    "range",
] }
moosicbox_menu = { path = "../menu" }
moosicbox_middleware = { path = "../middleware" }
moosicbox_player = { path = "../player", default-features = false, features = [
    "api",
] }
moosicbox_qobuz = { path = "../qobuz" }
moosicbox_scan = { path = "../scan", default-features = false, features = [
    "api",
    "local",
    "qobuz",
    "tidal",
] }
moosicbox_search = { path = "../search" }
moosicbox_tidal = { path = "../tidal" }
moosicbox_tunnel = { path = "../tunnel", default-features = false }
moosicbox_tunnel_sender = { path = "../tunnel_sender", default-features = false }
moosicbox_upnp = { path = "../upnp", optional = true, default-features = false, features = [
    "api",
    "listener",
] }
moosicbox_ws = { path = "../ws" }

# Postgres
aws-config = { workspace = true, optional = true }
aws-sdk-ssm = { workspace = true, optional = true }
native-tls = { workspace = true, optional = true }
openssl = { workspace = true, optional = true }
postgres-native-tls = { workspace = true, optional = true }
postgres-openssl = { workspace = true, optional = true }
sqlx = { workspace = true, optional = true, features = [
    "postgres",
    "runtime-tokio",
    "tls-rustls",
] }
tokio-postgres = { workspace = true, optional = true, features = [] }

# auth
qstring = { workspace = true, optional = true }

actix-cors      = { workspace = true }
actix-files     = { workspace = true }
actix-web       = { workspace = true }
actix-ws        = { workspace = true }
awc             = { workspace = true }
enum-as-inner   = { workspace = true }
flume           = { workspace = true }
free_log_client = { workspace = true }
futures         = { workspace = true }
futures-util    = { workspace = true }
kanal           = { workspace = true }
lazy_static     = { workspace = true }
log             = { workspace = true }
once_cell       = { workspace = true }
rand            = { workspace = true }
regex           = { workspace = true }
rusqlite        = { workspace = true }
serde           = { workspace = true, features = ["derive"] }
serde_json      = { workspace = true }
thiserror       = { workspace = true }
throttle        = { workspace = true }
tokio           = { workspace = true, features = ["macros", "rt", "time"] }
tokio-util      = { workspace = true }
url             = { workspace = true }

[features]
default = [
    "aac",
    "base64",
    "cpal",
    "flac",
    "mp3",
    "opus",
    "postgres-native-tls",
    "postgres-openssl",
    "postgres-raw",
    "postgres-sqlx",
    "pulseaudio",
    "sqlite",
    "static-token-auth",
    "upnp",
]

fail-on-warnings = []

base64 = ["moosicbox_tunnel/base64", "moosicbox_tunnel_sender/base64"]

# Player audio outputs
asio                = ["moosicbox_player/asio"]
cpal                = ["moosicbox_player/cpal"]
jack                = ["moosicbox_player/jack"]
pulseaudio          = ["moosicbox_player/pulseaudio"]
pulseaudio-simple   = ["moosicbox_player/pulseaudio-simple"]
pulseaudio-standard = ["moosicbox_player/pulseaudio-standard"]

static-token-auth = ["dep:qstring"]

aac = [
    "moosicbox_core/aac",
    "moosicbox_downloader/aac",
    "moosicbox_files/aac",
    "moosicbox_player/aac",
    "moosicbox_scan/aac",
    "moosicbox_tunnel_sender/aac",
]
flac = [
    "moosicbox_core/flac",
    "moosicbox_downloader/flac",
    "moosicbox_files/flac",
    "moosicbox_player/flac",
    "moosicbox_scan/flac",
    "moosicbox_tunnel_sender/flac",
]
mp3 = [
    "moosicbox_core/mp3",
    "moosicbox_downloader/mp3",
    "moosicbox_files/mp3",
    "moosicbox_player/mp3",
    "moosicbox_scan/mp3",
    "moosicbox_tunnel_sender/mp3",
]
opus = [
    "moosicbox_core/opus",
    "moosicbox_downloader/opus",
    "moosicbox_files/opus",
    "moosicbox_player/opus",
    "moosicbox_scan/opus",
    "moosicbox_tunnel_sender/opus",
]

postgres = ["dep:aws-config", "dep:aws-sdk-ssm", "moosicbox_database/postgres"]
postgres-native-tls = ["dep:native-tls", "dep:postgres-native-tls"]
postgres-openssl = ["dep:native-tls", "dep:openssl", "dep:postgres-openssl"]
postgres-raw = [
    "dep:tokio-postgres",
    "moosicbox_database/postgres-raw",
    "postgres",
]
postgres-sqlx = ["dep:sqlx", "moosicbox_database/postgres-sqlx", "postgres"]
sqlite = ["moosicbox_database/rusqlite"]

upnp = ["dep:moosicbox_upnp"]
