[build]
rustflags  = ["--cfg", "tokio_unstable"]
target-dir = "target"

[alias]
server           = "server:release"
"server:debug"   = "run"
"server:release" = "run --release"

[env]
RUST_LOG = "info"

[http]
timeout = 1000000

[net]
git-fetch-with-cli = true
