[package]
authors     = ["Braden Steffaniak"]
categories  = ["development-tools", "network-programming"]
description = "MoosicBox paging package"
edition     = "2021"
keywords    = ["api", "util", "utility"]
license     = "MPL-2.0"
name        = "moosicbox_paging"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBoxServer"
version     = "0.1.0"

[dependencies]
moosicbox_core = { path = "../core", default-features = false }

# API Dependencies
utoipa = { workspace = true, optional = true }

futures = { workspace = true }
log     = { workspace = true }
serde   = { workspace = true, features = ["derive"] }
tokio   = { workspace = true, features = ["macros"] }

[features]
default = ["openapi"]

fail-on-warnings = []

openapi = ["dep:utoipa"]
