[package]
authors     = ["Braden Steffaniak"]
categories  = ["development-tools", "multimedia"]
description = "MoosicBox package"
edition     = "2021"
keywords    = ["moosicbox"]
license     = "MPL-2.0"
name        = "moosicbox"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBoxServer"
version     = "0.1.0"

[dependencies]
moosicbox_assert        = { version = "0.1.0", path = "../assert", default-features = false }
moosicbox_async_service = { version = "0.1.0", path = "../async_service", default-features = false }
moosicbox_audio_decoder = { version = "0.1.0", path = "../audio_decoder", default-features = false }
moosicbox_audio_encoder = { version = "0.1.0", path = "../audio_encoder", default-features = false }
moosicbox_audio_output  = { version = "0.1.0", path = "../audio_output", default-features = false }
moosicbox_auth          = { version = "0.1.0", path = "../auth", default-features = false }
moosicbox_config        = { version = "0.1.0", path = "../config", default-features = false }
moosicbox_core          = { version = "0.1.0", path = "../core", default-features = false }
moosicbox_database      = { version = "0.1.0", path = "../database", default-features = false }
moosicbox_downloader    = { version = "0.1.0", path = "../downloader", default-features = false }
moosicbox_env_utils     = { version = "0.1.0", path = "../env_utils", default-features = false }
moosicbox_files         = { version = "0.1.0", path = "../files", default-features = false }
moosicbox_image         = { version = "0.1.0", path = "../image", default-features = false }
moosicbox_json_utils    = { version = "0.1.0", path = "../json_utils", default-features = false }
moosicbox_library       = { version = "0.1.0", path = "../library", default-features = false }
moosicbox_load_balancer = { version = "0.1.0", path = "../load_balancer", default-features = false }
moosicbox_logging       = { version = "0.1.0", path = "../logging", default-features = false }
moosicbox_menu          = { version = "0.1.0", path = "../menu", default-features = false }
moosicbox_middleware    = { version = "0.1.0", path = "../middleware", default-features = false }
moosicbox_music_api     = { version = "0.1.0", path = "../music_api", default-features = false }
moosicbox_paging        = { version = "0.1.0", path = "../paging", default-features = false }
moosicbox_player        = { version = "0.1.0", path = "../player", default-features = false }
moosicbox_qobuz         = { version = "0.1.0", path = "../qobuz", default-features = false }
moosicbox_resampler     = { version = "0.1.0", path = "../resampler", default-features = false }
moosicbox_scan          = { version = "0.1.0", path = "../scan", default-features = false }
moosicbox_search        = { version = "0.1.0", path = "../search", default-features = false }
moosicbox_session       = { version = "0.1.0", path = "../session", default-features = false }
moosicbox_stream_utils  = { version = "0.1.0", path = "../stream_utils", default-features = false }
moosicbox_task          = { version = "0.1.0", path = "../task", default-features = false }
moosicbox_tidal         = { version = "0.1.0", path = "../tidal", default-features = false }
moosicbox_tunnel        = { version = "0.1.0", path = "../tunnel", default-features = false }
moosicbox_tunnel_sender = { version = "0.1.0", path = "../tunnel_sender", default-features = false }
moosicbox_upnp          = { version = "0.1.0", path = "../upnp", default-features = false }
moosicbox_ws            = { version = "0.1.0", path = "../ws", default-features = false }
moosicbox_yt            = { version = "0.1.0", path = "../yt", default-features = false }

[features]
fail-on-warnings = []
