[package]
authors     = ["Braden Steffaniak"]
categories  = ["development-tools", "multimedia"]
description = "MoosicBox package"
edition     = "2021"
keywords    = ["moosicbox"]
license     = "MPL-2.0"
name        = "moosicbox"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBoxServer"
version     = "0.1.0"

[dependencies]
moosicbox_assert           = { workspace = true, default-features = false }
moosicbox_auth             = { workspace = true, default-features = false }
moosicbox_config           = { workspace = true, default-features = false }
moosicbox_converter        = { workspace = true, default-features = false }
moosicbox_core             = { workspace = true, default-features = false }
moosicbox_database         = { workspace = true, default-features = false }
moosicbox_downloader       = { workspace = true, default-features = false }
moosicbox_env_utils        = { workspace = true, default-features = false }
moosicbox_files            = { workspace = true, default-features = false }
moosicbox_image            = { workspace = true, default-features = false }
moosicbox_json_utils       = { workspace = true, default-features = false }
moosicbox_menu             = { workspace = true, default-features = false }
moosicbox_music_api        = { workspace = true, default-features = false }
moosicbox_paging           = { workspace = true, default-features = false }
moosicbox_player           = { workspace = true, default-features = false }
moosicbox_qobuz            = { workspace = true, default-features = false }
moosicbox_scan             = { workspace = true, default-features = false }
moosicbox_search           = { workspace = true, default-features = false }
moosicbox_stream_utils     = { workspace = true, default-features = false }
moosicbox_symphonia_player = { workspace = true, default-features = false }
moosicbox_tidal            = { workspace = true, default-features = false }
moosicbox_tunnel           = { workspace = true, default-features = false }
moosicbox_tunnel_sender    = { workspace = true, default-features = false }
moosicbox_upnp             = { workspace = true, default-features = false }
moosicbox_ws               = { workspace = true, default-features = false }

[features]
fail-on-warnings = []
