[package]
authors     = ["Braden Steffaniak"]
categories  = ["network-programming"]
description = "MoosicBox tunnel sender package"
edition     = "2021"
keywords    = ["api", "tunnel", "websocket"]
license     = "MPL-2.0"
name        = "moosicbox_tunnel_sender"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBoxServer"
version     = "0.1.0"

[dependencies]
moosicbox_assert = { workspace = true, default-features = false }
moosicbox_auth = { workspace = true }
moosicbox_core = { workspace = true, default-features = false }
moosicbox_database = { workspace = true, default-features = false, features = [
    "rusqlite",
] }
moosicbox_env_utils = { workspace = true }
moosicbox_files = { workspace = true, default-features = false, features = [
    "api",
    "files",
    "range",
] }
moosicbox_image = { workspace = true, default-features = false, features = [
    "image",
] }
moosicbox_stream_utils = { workspace = true }
moosicbox_symphonia_player = { workspace = true, default-features = false }
moosicbox_tunnel = { workspace = true, default-features = false }
moosicbox_ws = { workspace = true }

# Base64 dependencies
base64 = { workspace = true, optional = true }

bytes             = { workspace = true }
crossbeam-channel = { workspace = true }
futures-channel   = { workspace = true }
futures-util      = { workspace = true }
lazy_static       = { workspace = true }
log               = { workspace = true }
once_cell         = { workspace = true }
rand              = { workspace = true }
regex             = { workspace = true }
reqwest           = { workspace = true, features = ["json"] }
serde             = { workspace = true, features = ["derive"] }
serde-aux         = { workspace = true }
serde_json        = { workspace = true }
strum             = { workspace = true }
strum_macros      = { workspace = true }
symphonia         = { workspace = true }
thiserror         = { workspace = true }
tokio             = { workspace = true }
tokio-tungstenite = { workspace = true }
tokio-util        = { workspace = true }

[features]
default = ["aac", "base64", "flac", "mp3", "opus"]

fail-on-warnings = []

base64 = ["dep:base64", "moosicbox_tunnel/base64"]

aac = [
    "moosicbox_core/aac",
    "moosicbox_files/aac",
    "moosicbox_symphonia_player/aac",
]
flac = [
    "moosicbox_core/flac",
    "moosicbox_files/flac",
    "moosicbox_symphonia_player/flac",
]
mp3 = [
    "moosicbox_core/mp3",
    "moosicbox_files/mp3",
    "moosicbox_symphonia_player/mp3",
]
opus = [
    "moosicbox_core/opus",
    "moosicbox_files/opus",
    "moosicbox_symphonia_player/opus",
]
