[package]
authors     = ["Braden Steffaniak"]
categories  = ["development-tools"]
description = "MoosicBox clippier package"
edition     = "2021"
keywords    = ["clippier", "util", "utilities", "utils"]
license     = "MPL-2.0"
name        = "moosicbox_clippier"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBox"
version     = "0.1.0"

[[bin]]
name              = "moosicbox_clippier"
path              = "src/main.rs"
required-features = []

[dependencies]
moosicbox_logging = { path = "../logging", default-features = false }

clap       = { workspace = true }
itertools  = { workspace = true }
log        = { workspace = true }
serde      = { workspace = true }
serde_json = { workspace = true }
toml       = { workspace = true }

[features]
fail-on-warnings = []
