apiVersion: v1
kind: Service
metadata:
    name: moosicbox-service
    labels:
        run: moosicbox-service
spec:
    ports:
        - port: 8010
          targetPort: 8010
          protocol: TCP
    selector:
        run: moosicbox-service
