[package]
authors     = ["Braden Steffaniak"]
categories  = ["encoding", "multimedia", "network-programming"]
description = "MoosicBox Symphomia player package"
edition     = "2021"
keywords    = ["audio", "bytes", "decoder", "file", "remote", "stream"]
license     = "MPL-2.0"
name        = "moosicbox_symphonia_player"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBoxServer"
version     = "0.1.0"

[dependencies]
moosicbox_assert       = { path = "../assert", default-features = false }
moosicbox_converter    = { path = "../converter", default-features = false }
moosicbox_env_utils    = { path = "../env_utils" }
moosicbox_stream_utils = { path = "../stream_utils" }

arrayvec                = { workspace = true }
atomic_float            = { workspace = true }
bytes                   = { workspace = true }
clap                    = { workspace = true }
cpal                    = { workspace = true, optional = true }
crossbeam-channel       = { workspace = true }
fdk-aac                 = { workspace = true, optional = true }
flume                   = { workspace = true }
futures                 = { workspace = true }
lazy_static             = { workspace = true }
libpulse-binding        = { workspace = true, optional = true }
libpulse-simple-binding = { workspace = true, optional = true }
log                     = { workspace = true }
mp3lame-encoder         = { workspace = true, optional = true }
ogg                     = { workspace = true, optional = true }
opus                    = { workspace = true, optional = true }
pretty_env_logger       = { workspace = true }
rangemap                = { workspace = true }
rb                      = { workspace = true }
reqwest                 = { workspace = true }
rubato                  = { workspace = true }
symphonia               = { workspace = true }
thiserror               = { workspace = true }
tokio                   = { workspace = true, features = ["rt-multi-thread"] }
tokio-stream            = { workspace = true }
tokio-util              = { workspace = true }

[features]
default = [
    "aac",
    "cpal",
    "flac",
    "mp3",
    "oboe-shared-stdcxx",
    "opus",
    "pulseaudio",
]

fail-on-warnings = []

# Player audio outputs
asio                = ["cpal/asio"]
cpal                = ["dep:cpal"]
jack                = ["cpal/jack"]
oboe-shared-stdcxx  = ["cpal/oboe-shared-stdcxx"]
pulseaudio          = ["pulseaudio-simple", "pulseaudio-standard"]
pulseaudio-simple   = ["dep:libpulse-binding", "dep:libpulse-simple-binding"]
pulseaudio-standard = ["dep:libpulse-binding", "dep:libpulse-simple-binding"]

aac  = ["dep:fdk-aac", "moosicbox_converter/aac"]
flac = ["moosicbox_converter/flac"]
mp3  = ["dep:mp3lame-encoder", "moosicbox_converter/mp3"]
opus = ["dep:ogg", "dep:opus", "moosicbox_converter/opus"]
