[package]
authors     = ["Braden Steffaniak"]
categories  = ["gui"]
description = "Giga-Chad egui renderer package"
edition     = "2021"
keywords    = ["desktop", "egui", "gui", "render", "renderer"]
license     = "MPL-2.0"
name        = "gigachad_renderer_egui"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBox"
version     = "0.1.0"

[package.metadata.cargo-machete]
ignored = ["image"]

[dependencies]
gigachad_renderer = { version = "0.1.0", path = "../", default-features = false, features = [
    "viewport-immediate",
] }
gigachad_transformer = { version = "0.1.0", path = "../../transformer", default-features = false, features = [
    "calc",
    "html",
    "id",
] }
moosicbox_app_native_image = { version = "0.1.0", path = "../../../app/native/image", default-features = false }
moosicbox_assert = { version = "0.1.0", path = "../../../assert", default-features = false }
moosicbox_logging = { version = "0.1.0", path = "../../../logging", default-features = false, features = [
    "macros",
] }
moosicbox_task = { version = "0.1.0", path = "../../../task", default-features = false }

async-trait = { workspace = true }
eframe = { workspace = true, default-features = false, features = [
    "__screenshot",
    "default",
] }
egui_extras = { workspace = true, features = ["image"] }
flume = { workspace = true }
image = { workspace = true, features = ["webp"] }
itertools = { workspace = true }
log = { workspace = true }
reqwest = { workspace = true }

[features]
default = ["debug", "wgpu"]

fail-on-warnings = []

wgpu = ["eframe/wgpu"]

debug = []
