[package]
authors     = ["Braden Steffaniak"]
categories  = ["development-tools", "gui", "web-programming"]
description = "MoosicBox htmx transformer package"
edition     = "2021"
keywords    = ["dom", "gui", "html", "htmx", "transformer", "web"]
license     = "MPL-2.0"
name        = "moosicbox_htmx_transformer"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBoxServer"
version     = "0.1.0"

[dependencies]
tl = { workspace = true, optional = true }

[features]
default = ["html"]

fail-on-warnings = []

html = ["dep:tl"]
simd = ["tl?/simd"]
