[package]
authors     = ["Braden Steffaniak"]
categories  = ["gui"]
description = "MoosicBox fltk renderer package"
edition     = "2021"
keywords    = ["desktop", "gui", "linux", "macos", "render", "renderer", "windows"]
license     = "MPL-2.0"
name        = "moosicbox_renderer_fltk"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBoxServer"
version     = "0.1.0"

[dependencies]
moosicbox_htmx_transformer = { path = "../htmx_transformer", default-features = false, features = [
    "html",
] }

fltk    = { workspace = true }
flume   = { workspace = true }
futures = { workspace = true }
log     = { workspace = true }

[features]
default = ["unsafe"]

fail-on-warnings = []

unsafe = []
