[package]
authors     = ["Braden Steffaniak"]
categories  = ["multimedia", "network-programming"]
description = "MoosicBox scan package"
edition     = "2021"
keywords    = ["audio", "files", "local", "remote", "scan"]
license     = "MPL-2.0"
name        = "moosicbox_scan"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBoxServer"
version     = "0.1.0"

[dependencies]
moosicbox_assert = { path = "../assert", default-features = false }
moosicbox_config = { path = "../config" }
moosicbox_core = { path = "../core", default-features = false }
moosicbox_database = { path = "../database", default-features = false, features = [
    "rusqlite",
] }
moosicbox_files = { path = "../files", default-features = false }
moosicbox_json_utils = { path = "../json_utils", default-features = false, features = [
    "serde_json",
] }
moosicbox_search = { path = "../search" }

# API Dependencies
actix-web = { workspace = true, optional = true }

# Qobuz Dependencies
moosicbox_qobuz = { path = "../qobuz", optional = true }

# Tidal Dependencies
moosicbox_tidal = { path = "../tidal", optional = true }

# Local Dependencies
audiotags    = { workspace = true, optional = true }
lofty        = { workspace = true, optional = true }
mp3-duration = { workspace = true, optional = true }

futures      = { workspace = true }
log          = { workspace = true }
once_cell    = { workspace = true }
regex        = { workspace = true }
reqwest      = { workspace = true }
rusqlite     = { workspace = true }
serde        = { workspace = true, features = ["derive"] }
serde_json   = { workspace = true }
strum        = { workspace = true }
strum_macros = { workspace = true }
thiserror    = { workspace = true }
tokio        = { workspace = true, features = ["macros"] }
tokio-util   = { workspace = true }

[features]
default = ["aac", "api", "flac", "local", "mp3", "opus", "qobuz", "tidal"]

fail-on-warnings = []

api   = ["dep:actix-web"]
local = ["dep:audiotags", "dep:lofty", "dep:mp3-duration"]
qobuz = ["dep:moosicbox_qobuz"]
tidal = ["dep:moosicbox_tidal"]

aac  = ["moosicbox_core/aac"]
flac = ["moosicbox_core/flac"]
mp3  = ["moosicbox_core/mp3"]
opus = ["moosicbox_core/opus"]
