[package]
authors     = ["Braden Steffaniak"]
categories  = ["multimedia", "network-programming"]
description = "MoosicBox scan package"
edition     = "2021"
keywords    = ["audio", "files", "local", "remote", "scan"]
license     = "MPL-2.0"
name        = "moosicbox_scan"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBox"
version     = "0.1.0"

[package.metadata.cargo-machete]
ignored = ["strum"]

[dependencies]
moosicbox_assert = { version = "0.1.0", path = "../assert", default-features = false }
moosicbox_config = { version = "0.1.0", path = "../config", default-features = false }
moosicbox_core = { version = "0.1.0", path = "../core", default-features = false }
moosicbox_database = { version = "0.1.0", path = "../database", default-features = false }
moosicbox_files = { version = "0.1.0", path = "../files", default-features = false }
moosicbox_json_utils = { version = "0.1.0", path = "../json_utils", default-features = false, features = [
    "serde_json",
] }
moosicbox_library = { version = "0.1.0", path = "../library", default-features = false }
moosicbox_music_api = { version = "0.1.0", path = "../music_api", default-features = false }
moosicbox_paging = { version = "0.1.0", path = "../paging" }
moosicbox_search = { version = "0.1.0", path = "../search" }
moosicbox_task = { version = "0.1.0", path = "../task", default-features = false }

# API Dependencies
actix-web      = { workspace = true, optional = true }
moosicbox_auth = { version = "0.1.0", path = "../auth", default-features = false, optional = true }
utoipa         = { workspace = true, optional = true }

# Local Dependencies
async-recursion     = { workspace = true, optional = true }
moosicbox_audiotags = { workspace = true, optional = true }
moosicbox_lofty     = { workspace = true, optional = true }
mp3-duration        = { workspace = true, optional = true }

futures      = { workspace = true }
log          = { workspace = true }
regex        = { workspace = true }
reqwest      = { workspace = true }
serde        = { workspace = true, features = ["derive"] }
serde_json   = { workspace = true }
strum        = { workspace = true }
strum_macros = { workspace = true }
thiserror    = { workspace = true }
tokio        = { workspace = true, features = ["macros", "tracing"] }
tokio-util   = { workspace = true }

[features]
default = [
    "aac",
    "all-sources",
    "api",
    "flac",
    "local",
    "mp3",
    "openapi",
    "opus",
]

fail-on-warnings = []

api = ["dep:actix-web", "dep:moosicbox_auth", "moosicbox_music_api/api"]
local = [
    "dep:async-recursion",
    "dep:moosicbox_audiotags",
    "dep:moosicbox_lofty",
    "dep:mp3-duration",
]
openapi = ["dep:utoipa"]

aac  = ["moosicbox_core/aac", "moosicbox_library/aac"]
flac = ["moosicbox_core/flac", "moosicbox_library/flac"]
mp3  = ["moosicbox_core/mp3", "moosicbox_library/mp3"]
opus = ["moosicbox_core/opus", "moosicbox_library/opus"]

all-sources = ["qobuz", "tidal", "yt"]

qobuz = ["moosicbox_core/qobuz", "moosicbox_library/qobuz"]
tidal = ["moosicbox_core/tidal", "moosicbox_library/tidal"]
yt    = ["moosicbox_core/yt", "moosicbox_library/yt"]
