[package]
authors = ["Braden Steffaniak"]
edition = "2021"
name    = "moosicbox_scan"
version = "0.1.0"

[dependencies]
moosicbox_core = { path = "../core" }

# API Dependencies
actix-web = { workspace = true, optional = true }

# Tidal Dependencies
moosicbox_tidal = { path = "../tidal", optional = true }
reqwest         = { workspace = true, optional = true }

# Local Dependencies
audiotags    = { workspace = true, optional = true }
lofty        = { workspace = true, optional = true }
mp3-duration = { workspace = true, optional = true }

futures      = { workspace = true }
home         = { workspace = true }
log          = { workspace = true }
once_cell    = { workspace = true }
regex        = { workspace = true }
rusqlite     = { workspace = true }
serde        = { workspace = true, features = ["derive"] }
serde_json   = { workspace = true }
strum        = { workspace = true }
strum_macros = { workspace = true }
thiserror    = { workspace = true }
tokio        = { workspace = true }
tokio-util   = { workspace = true }

[features]
default = ["api", "local", "tidal"]

fail-on-warnings = []

api   = ["dep:actix-web"]
local = ["dep:audiotags", "dep:lofty", "dep:mp3-duration"]
tidal = ["dep:moosicbox_tidal", "dep:reqwest"]
