[package]
authors = ["Braden Steffaniak"]
edition = "2021"
name    = "moosicbox_scan"
version = "0.1.0"

[dependencies]
moosicbox_core = { path = "../core" }

# API Dependencies
actix-web = { workspace = true, optional = true }

audiotags    = { workspace = true }
bytes        = { workspace = true }
futures      = { workspace = true }
lofty        = { workspace = true }
log          = { workspace = true }
mp3-duration = { workspace = true }
once_cell    = { workspace = true }
regex        = { workspace = true }
rusqlite     = { workspace = true }
serde        = { workspace = true, features = ["derive"] }
serde_json   = { workspace = true }
strum        = { workspace = true }
strum_macros = { workspace = true }
thiserror    = { workspace = true }
tokio        = { workspace = true }
tokio-util   = { workspace = true }

[features]
default = ["api", "local", "tidal"]

fail-on-warnings = []

api   = ["dep:actix-web"]
local = []
tidal = []
