[package]
authors     = ["Braden Steffaniak"]
categories  = ["multimedia", "network-programming"]
description = "MoosicBox scan package"
edition     = "2021"
keywords    = ["audio", "files", "local", "remote", "scan"]
license     = "MPL-2.0"
name        = "moosicbox_scan"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBoxServer"
version     = "0.1.0"

[dependencies]
moosicbox_assert = { path = "../assert", default-features = false }
moosicbox_config = { path = "../config" }
moosicbox_core = { path = "../core", default-features = false }
moosicbox_database = { path = "../database", default-features = false, features = [
    "rusqlite",
] }
moosicbox_files = { path = "../files", default-features = false }
moosicbox_json_utils = { path = "../json_utils", default-features = false, features = [
    "serde_json",
] }
moosicbox_library = { path = "../library", default-features = false }
moosicbox_music_api = { path = "../music_api", default-features = false }
moosicbox_paging = { path = "../paging" }
moosicbox_search = { path = "../search" }
moosicbox_task = { path = "../task", default-features = false }

# API Dependencies
actix-web      = { workspace = true, optional = true }
moosicbox_auth = { path = "../auth", default-features = false, optional = true }
utoipa         = { workspace = true, optional = true }

# Local Dependencies
async-recursion = { workspace = true, optional = true }
audiotags       = { workspace = true, optional = true }
lofty           = { workspace = true, optional = true }
mp3-duration    = { workspace = true, optional = true }

futures      = { workspace = true }
log          = { workspace = true }
once_cell    = { workspace = true }
regex        = { workspace = true }
reqwest      = { workspace = true }
rusqlite     = { workspace = true }
serde        = { workspace = true, features = ["derive"] }
serde_json   = { workspace = true }
strum        = { workspace = true }
strum_macros = { workspace = true }
thiserror    = { workspace = true }
tokio        = { workspace = true, features = ["macros", "tracing"] }
tokio-util   = { workspace = true }

[features]
default = ["aac", "api", "flac", "local", "mp3", "openapi", "opus"]

fail-on-warnings = []

api = ["dep:actix-web", "dep:moosicbox_auth"]
local = [
    "dep:async-recursion",
    "dep:audiotags",
    "dep:lofty",
    "dep:mp3-duration",
]
openapi = ["dep:utoipa"]

aac  = ["moosicbox_core/aac", "moosicbox_library/aac"]
flac = ["moosicbox_core/flac", "moosicbox_library/flac"]
mp3  = ["moosicbox_core/mp3", "moosicbox_library/mp3"]
opus = ["moosicbox_core/opus", "moosicbox_library/opus"]
