[package]
authors     = ["Braden Steffaniak"]
categories  = ["development-tools"]
description = "MoosicBox Session models package"
edition     = "2021"
keywords    = ["models", "session", "state"]
license     = "MPL-2.0"
name        = "moosicbox_session_models"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBox"
version     = "0.1.0"

[package.metadata.cargo-machete]
ignored = ["strum"]

[dependencies]
moosicbox_audio_zone_models = { version = "0.1.0", path = "../../audio_zone/models", default-features = false }
moosicbox_core              = { version = "0.1.0", path = "../../core", default-features = false }
moosicbox_database          = { version = "0.1.0", path = "../../database", default-features = false }
moosicbox_json_utils        = { version = "0.1.0", path = "../../json_utils", default-features = false }

# API Dependencies
utoipa = { workspace = true, optional = true }

log          = { workspace = true }
serde        = { workspace = true, features = ["derive"] }
strum        = { workspace = true }
strum_macros = { workspace = true }

[features]
default = ["all-sources", "api", "openapi"]

fail-on-warnings = []

api = ["moosicbox_database/api"]
openapi = [
    "dep:utoipa",
    "moosicbox_audio_zone_models/openapi",
    "moosicbox_core/openapi",
]

aac  = []
flac = []
mp3  = []
opus = []

all-sources = ["qobuz", "tidal", "yt"]

qobuz = ["moosicbox_core/qobuz"]
tidal = ["moosicbox_core/tidal"]
yt    = ["moosicbox_core/yt"]
