[package]
authors     = ["Braden Steffaniak"]
categories  = ["gui"]
description = "GigaChad renderer package"
edition     = "2021"
keywords    = ["desktop", "gui", "render", "renderer"]
license     = "MPL-2.0"
name        = "gigachad_renderer"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBox"
version     = "0.1.0"

[dependencies]
gigachad_color = { version = "0.1.0", path = "../color", default-features = false }
gigachad_transformer = { version = "0.1.0", path = "../transformer", default-features = false, features = [
    "html",
] }

async-trait = { workspace = true }
log         = { workspace = true }
maud        = { workspace = true, optional = true }

[features]
default = [
    "canvas",
    "maud",
    "viewport",
    "viewport-immediate",
    "viewport-retained",
]

fail-on-warnings = []

maud = ["dep:maud", "gigachad_transformer/maud"]

canvas = ["gigachad_transformer/canvas"]

viewport           = []
viewport-immediate = ["viewport"]
viewport-retained  = ["viewport"]
