[package]
authors = ["Braden Steffaniak"]
edition = "2021"
name    = "moosicbox_converter"
version = "0.1.0"

[dependencies]
audiopus        = { workspace = true }
fdk-aac         = { workspace = true }
log             = { workspace = true }
mp3lame-encoder = { workspace = true }
ogg             = { workspace = true }
opus            = { workspace = true }
thiserror       = { workspace = true }

[features]
default = ["aac", "mp3", "opus"]

fail-on-warnings = []

aac  = []
mp3  = []
opus = []
