[package]
authors     = ["Braden Steffaniak"]
categories  = ["compression", "encoding"]
description = "Audio converter helper"
edition     = "2021"
keywords    = ["audio", "convert", "converter", "encoding"]
license     = "MPL-2.0"
name        = "moosicbox_converter"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBoxServer"
version     = "0.1.0"

[dependencies]
# Aac dependencies
fdk-aac = { workspace = true, optional = true }

# Opus dependencies
audiopus = { workspace = true, optional = true }
ogg      = { workspace = true, optional = true }
opus     = { workspace = true, optional = true }

# Mp3 dependencies
mp3lame-encoder = { workspace = true, optional = true }

log       = { workspace = true }
thiserror = { workspace = true }

[features]
default = ["aac", "mp3", "opus"]

fail-on-warnings = []

aac  = ["dep:fdk-aac"]
mp3  = ["dep:mp3lame-encoder"]
opus = ["dep:audiopus", "dep:ogg", "dep:opus"]
