[package]
authors     = ["Braden Steffaniak"]
categories  = ["development-tools"]
description = "MoosicBox logging package"
edition     = "2021"
keywords    = ["log", "logger", "logging"]
license     = "MPL-2.0"
name        = "moosicbox_logging"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBoxServer"
version     = "0.1.0"

[dependencies]
moosicbox_assert    = { path = "../assert", default-features = false }
moosicbox_config    = { path = "../config", default-features = false }
moosicbox_env_utils = { path = "../env_utils", default-features = false }

free_log_client = { workspace = true }
log             = { workspace = true }
thiserror       = { workspace = true }

[features]
fail-on-warnings = []
