[package]
authors = ["Braden Steffaniak"]
edition = "2021"
name    = "moosicbox_config"
version = "0.1.0"

[dependencies]
home      = { workspace = true }
log       = { workspace = true }
thiserror = { workspace = true }

[features]
fail-on-warnings = []
