[package]
authors     = ["Braden Steffaniak"]
categories  = ["configuration"]
description = "MoosicBox configuration package"
edition     = "2021"
keywords    = ["config", "configuration"]
license     = "MPL-2.0"
name        = "moosicbox_config"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBoxServer"
version     = "0.1.0"

[dependencies]
# DB dependencies
moosicbox_database = { path = "../database", optional = true, default-features = false, features = [
    "api",
] }
moosicbox_json_utils = { path = "../json_utils", optional = true, default-features = false, features = [
    "database",
] }
nanoid = { workspace = true, optional = true }

# API dependencies
actix-web = { workspace = true, optional = true }
serde     = { workspace = true, optional = true }
utoipa    = { workspace = true, optional = true }

# Test dependencies
rand = { workspace = true, optional = true }

home      = { workspace = true }
log       = { workspace = true }
thiserror = { workspace = true }

[features]
default = ["api", "db", "openapi"]

fail-on-warnings = []

test = ["dep:rand"]

db = ["dep:moosicbox_database", "dep:moosicbox_json_utils", "dep:nanoid"]

api     = ["db", "dep:actix-web", "dep:serde"]
openapi = ["dep:utoipa"]
