[package]
authors     = ["Braden Steffaniak"]
categories  = ["development-tools", "multimedia", "network-programming"]
description = "MoosicBox music API package"
edition     = "2021"
keywords    = ["album", "api", "artist", "music", "playlist", "track"]
license     = "MPL-2.0"
name        = "moosicbox_music_api"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBoxServer"
version     = "0.1.0"

[package.metadata.cargo-machete]
ignored = ["strum"]

[dependencies]
moosicbox_core = { path = "../core", default-features = false }
moosicbox_database = { path = "../database", default-features = false }
moosicbox_json_utils = { path = "../json_utils", default-features = false, features = [
    "serde_json",
] }
moosicbox_paging = { path = "../paging", default-features = false }

# API Dependencies
actix-web = { workspace = true, optional = true }
utoipa    = { workspace = true, optional = true }

async-trait  = { workspace = true }
futures      = { workspace = true }
log          = { workspace = true }
serde        = { workspace = true, features = ["derive"] }
serde_json   = { workspace = true }
strum        = { workspace = true }
strum_macros = { workspace = true }
thiserror    = { workspace = true }
tokio        = { workspace = true, features = ["macros"] }

[dev-dependencies]
pretty_assertions = { workspace = true }
test-log          = { workspace = true }

[features]
default = ["api", "db", "openapi"]

fail-on-warnings = []

openapi = ["dep:utoipa"]

db = ["moosicbox_database/api"]

api = ["dep:actix-web", "moosicbox_database/api"]
