[package]
authors     = ["Braden Steffaniak"]
categories  = ["gui"]
description = "MoosicBox native fltk App package"
edition     = "2021"
keywords    = ["app", "desktop", "gui", "linux", "macos", "native", "windows"]
license     = "MPL-2.0"
name        = "moosicbox_app_native"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBoxServer"
version     = "0.1.0"

[[bin]]
name              = "moosicbox_app_native"
path              = "src/main.rs"
required-features = []

[dependencies]
moosicbox_app_native_lib = { path = "lib", default-features = false }
moosicbox_app_native_ui = { path = "ui", default-features = false }
moosicbox_env_utils = { path = "../../env_utils", default-features = false }
moosicbox_library_models = { path = "../../library/models", default-features = false, features = [
    "all-formats",
] }
moosicbox_logging = { path = "../../logging", default-features = false }
moosicbox_paging = { path = "../../paging", default-features = false }

# Bundled dependencies
moosicbox_app_native_bundled = { path = "bundled", optional = true, default-features = false }

log     = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
tokio   = { workspace = true, features = ["macros", "rt-multi-thread"] }

[features]
default = ["unsafe"]

fail-on-warnings = []

bundled = ["dep:moosicbox_app_native_bundled"]

unsafe = []
