[package]
authors     = ["Braden Steffaniak"]
categories  = ["gui"]
description = "MoosicBox native App package"
edition     = "2021"
keywords    = ["app", "desktop", "gui", "native"]
license     = "MPL-2.0"
name        = "moosicbox_app_native"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBox"
version     = "0.1.0"

[[bin]]
name              = "moosicbox_app_native"
path              = "src/main.rs"
required-features = []

[package.metadata.bundle]
category          = "Music"
copyright         = "Copyright (c) Braden Steffaniak 2024. All rights reserved."
deb_depends       = []
icon              = ["128x128.png", "128x128@2x.png", "32x32.png"]
identifier        = "com.moosicbox.app"
name              = "MoosicBox"
resources         = []
short_description = "A music app for cows"

[package.metadata.wix]
compiler-args = ["-nologo"]
dbg-build     = false
dbg-name      = false
eula          = false
linker-args   = ["-nologo"]
name          = "MoosicBox"
no-build      = false
product-name  = "MoosicBox"

[dependencies]
moosicbox_app_native_lib = { version = "0.1.0", path = "lib", default-features = false, features = [
    "maud",
] }
moosicbox_app_native_ui = { version = "0.1.0", path = "ui", default-features = false }
moosicbox_app_state = { version = "0.1.0", path = "../state", default-features = false }
moosicbox_assert = { version = "0.1.0", path = "../../assert", default-features = false }
moosicbox_core = { version = "0.1.0", path = "../../core", default-features = false }
moosicbox_env_utils = { version = "0.1.0", path = "../../env_utils", default-features = false }
moosicbox_logging = { version = "0.1.0", path = "../../logging", default-features = false, features = [
    "free_log",
] }
moosicbox_music_api = { version = "0.1.0", path = "../../music_api", default-features = false }
moosicbox_paging = { version = "0.1.0", path = "../../paging", default-features = false }
moosicbox_player = { version = "0.1.0", path = "../../player", default-features = false }
moosicbox_remote_library = { version = "0.1.0", path = "../../remote_library", default-features = false }
moosicbox_session_models = { version = "0.1.0", path = "../../session/models", default-features = false }
moosicbox_task = { version = "0.1.0", path = "../../task", default-features = false }
moosicbox_ws = { version = "0.1.0", path = "../../ws", default-features = false }

# Bundled dependencies
moosicbox_app_native_bundled = { version = "0.1.0", path = "bundled", optional = true, default-features = false }

console-subscriber = { workspace = true }
flume              = { workspace = true }
log                = { workspace = true }
reqwest            = { workspace = true, features = ["json"] }
serde_json         = { workspace = true }
strum              = { workspace = true }
thiserror          = { workspace = true }
tokio              = { workspace = true, features = ["macros", "rt-multi-thread"] }
tokio-util         = { workspace = true }

[features]
default = [
    "all-formats",
    "all-sources",
    "datastar",
    "egui-wgpu",
    "fltk",
    "html",
    "htmx",
    "unsafe",
    "vanilla-js",
]

fail-on-warnings = []

_calculated_canvas = ["_canvas"]
_canvas            = []

datastar   = ["_canvas", "moosicbox_app_native_lib/datastar"]
egui       = ["_calculated_canvas", "moosicbox_app_native_lib/egui"]
egui-wgpu  = ["egui", "moosicbox_app_native_lib/egui-wgpu"]
fltk       = ["_calculated_canvas", "moosicbox_app_native_lib/fltk"]
html       = ["_canvas", "moosicbox_app_native_lib/html"]
htmx       = ["_canvas", "moosicbox_app_native_lib/htmx"]
vanilla-js = ["_canvas", "moosicbox_app_native_lib/vanilla-js"]

bundled = ["all-sources", "dep:moosicbox_app_native_bundled"]

windows-console = []

debug             = ["moosicbox_app_native_lib/debug"]
format            = ["moosicbox_app_native_lib/format"]
profiling-puffin  = ["moosicbox_app_native_lib/profiling-puffin"]
profiling-tracing = ["moosicbox_app_native_lib/profiling-tracing"]
profiling-tracy   = ["moosicbox_app_native_lib/profiling-tracy"]
unsafe            = ["moosicbox_app_native_lib/unsafe"]

all-formats = ["aac", "flac", "mp3", "opus"]

aac  = ["moosicbox_core/aac"]
flac = ["moosicbox_core/flac"]
mp3  = ["moosicbox_core/mp3"]
opus = ["moosicbox_core/opus"]

all-sources = ["qobuz", "tidal", "yt"]

qobuz = [
    "moosicbox_app_native_ui/qobuz",
    "moosicbox_app_state/qobuz",
    "moosicbox_core/qobuz",
    "moosicbox_session_models/qobuz",
]
tidal = [
    "moosicbox_app_native_ui/tidal",
    "moosicbox_app_state/tidal",
    "moosicbox_core/tidal",
    "moosicbox_session_models/tidal",
]
yt = [
    "moosicbox_app_native_ui/yt",
    "moosicbox_app_state/yt",
    "moosicbox_core/yt",
    "moosicbox_session_models/yt",
]
