[build]
target-dir = "target"

[alias]
"server:debug" = "run --no-default-features --features=server"
"server:release" = "run --no-default-features --features=server --release"
server = "server:release"

[env]
RUST_LOG = "info"

[http]
timeout = 1000000

[net]
git-fetch-with-cli = true
