[build]
target-dir = "target"

[alias]
"server:debug" = "run"
"server:release" = "run --release"
server = "server:release"

[env]
RUST_LOG = "info"

[http]
timeout = 1000000

[net]
git-fetch-with-cli = true
