[package]
authors     = ["Braden Steffaniak"]
categories  = ["encoding", "multimedia", "network-programming"]
description = "MoosicBox Symphomia player package"
edition     = "2021"
keywords    = ["audio", "bytes", "decoder", "file", "remote", "stream"]
license     = "MPL-2.0"
name        = "moosicbox_audio_decoder"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBoxServer"
version     = "0.1.0"

[dependencies]
moosicbox_assert = { path = "../assert", default-features = false }
moosicbox_audio_output = { path = "../audio_output", default-features = false }
moosicbox_converter = { path = "../converter", default-features = false }
moosicbox_env_utils = { path = "../env_utils", default-features = false }
moosicbox_resampler = { path = "../resampler", default-features = false }
moosicbox_stream_utils = { path = "../stream_utils", default-features = false, features = [
    "remote-bytestream",
    "stalled-monitor",
] }
moosicbox_task = { path = "../task", default-features = false }

arrayvec          = { workspace = true }
atomic_float      = { workspace = true }
bytes             = { workspace = true }
clap              = { workspace = true }
flume             = { workspace = true }
futures           = { workspace = true }
lazy_static       = { workspace = true }
log               = { workspace = true }
pretty_env_logger = { workspace = true }
rangemap          = { workspace = true }
reqwest           = { workspace = true }
symphonia         = { workspace = true }
thiserror         = { workspace = true }
tokio             = { workspace = true, features = ["rt-multi-thread", "tracing"] }
tokio-stream      = { workspace = true }
tokio-util        = { workspace = true }

[features]
default = ["aac", "flac", "mp3", "opus"]

fail-on-warnings = []

aac  = ["moosicbox_audio_output/aac"]
flac = ["moosicbox_audio_output/flac"]
mp3  = ["moosicbox_audio_output/mp3"]
opus = ["moosicbox_audio_output/opus"]
