[package]
authors     = ["Braden Steffaniak"]
categories  = ["encoding", "multimedia", "network-programming"]
description = "MoosicBox Symphomia player package"
edition     = "2021"
keywords    = ["audio", "bytes", "decoder", "file", "remote", "stream"]
license     = "MPL-2.0"
name        = "moosicbox_audio_decoder"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBox"
version     = "0.1.0"

[dependencies]
moosicbox_stream_utils = { path = "../stream_utils", default-features = false, features = [
    "remote-bytestream",
    "stalled-monitor",
] }
moosicbox_task = { path = "../task", default-features = false }

bytes      = { workspace = true }
flume      = { workspace = true }
futures    = { workspace = true }
log        = { workspace = true }
rangemap   = { workspace = true }
reqwest    = { workspace = true }
symphonia  = { workspace = true }
thiserror  = { workspace = true }
tokio      = { workspace = true, features = ["rt-multi-thread", "tracing"] }
tokio-util = { workspace = true }

[features]
default = []

fail-on-warnings = []
