name: Auto-upgrade Incompatible Dependencies

on:
    workflow_dispatch:
    schedule:
        - cron: '0 3 * * *'

env:
    CARGO_TERM_COLOR: always
    AWS_REGION: us-east-1

jobs:
    upgrade:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  token: ${{ secrets.MOOSICBOX_BOT_UPGRADES_TOKEN }}

            - uses: dtolnay/rust-toolchain@stable

            - name: Install cargo-edit
              shell: bash
              run: |
                  cargo install \
                      -f cargo-edit \
                      --git https://github.com/BSteffaniak/cargo-edit \
                      --branch add-skip-git-dependencies

            - name: Upgrade
              id: upgrade
              shell: bash
              run: |
                  cargo upgrade --skip-git-dependencies --incompatible
                  cargo update
                  if [ -n "$(git status --porcelain)" ]; then
                      echo "Found upgrades"
                      echo "upgraded=true" >> "$GITHUB_OUTPUT"
                  else
                      echo "No upgrades"
                      echo "upgraded=false" >> "$GITHUB_OUTPUT"
                  fi

            - name: Build
              if: ${{ steps.upgrade.outputs.upgraded == 'true'}}
              shell: bash
              run: |
                  sudo apt-get update && sudo apt-get install \
                      curl \
                      wget \
                      file \
                      libssl-dev \
                      libayatana-appindicator3-dev \
                      librsvg2-dev \
                      libasound2-dev \
                      libwebkit2gtk-4.1-dev \
                      build-essential \
                      libx11-dev \
                      libxext-dev \
                      libxft-dev \
                      libxinerama-dev \
                      libxcursor-dev \
                      libxrender-dev \
                      libxfixes-dev \
                      libpango1.0-dev \
                      libgl1-mesa-dev \
                      libglu1-mesa-dev \
                      libgtk-3-dev \
                      libsoup-3.0-dev\
                      pulseaudio \
                      libvips-dev
                  STATIC_TOKEN=123 TUNNEL_ACCESS_TOKEN=123 cargo build

            - name: Test
              if: ${{ steps.upgrade.outputs.upgraded == 'true'}}
              shell: bash
              run: |
                  STATIC_TOKEN=123 TUNNEL_ACCESS_TOKEN=123 cargo test

            - name: Commit
              if: ${{ steps.upgrade.outputs.upgraded == 'true'}}
              shell: bash
              run: |
                  git config user.name "MoosicBoxBot"
                  git config user.email "MoosicBoxBot@gmail.com"
                  git add .
                  git commit --message "Upgrade Incompatible Dependencies"
                  echo "Pushing upgrades"
                  git push origin master
