name: Build and Test

on:
    push:
        branches: ['master']
    pull_request:
        branches: ['master']

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false

            matrix:
                package:
                    - name: core
                      path: packages/core

                    - name: files
                      path: packages/files

                    - name: menu
                      path: packages/menu

                    - name: player
                      path: packages/player
                      dependencies: libasound2-dev
                      features: cpal

                    - name: ws
                      path: packages/ws

                    - name: server
                      path: server
                      dependencies: libasound2-dev
                      features: cpal

                    - name: symphonia_player cpal
                      path: players/symphonia_player
                      dependencies: libasound2-dev
                      features: cpal

                    - name: symphonia_player pulseaudio-standard
                      path: players/symphonia_player
                      dependencies: pulseaudio
                      features: pulseaudio-standard

                    - name: symphonia_player pulseaudio-simple
                      path: players/symphonia_player
                      dependencies: pulseaudio
                      features: pulseaudio-simple

        steps:
            - name: Checkout audiotags
              uses: actions/checkout@master
              with:
                  repository: BSteffaniak/audiotags
                  ref: feat/add-full-date-capabilities
                  path: audiotags

            - uses: actions/checkout@v3
              with:
                  path: MoosicBoxServer

            - name: ⚡ Cache cargo
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.cargo/registry
                      ~/.cargo/git
                      target
                  key: ${{ runner.os }}-${{ matrix.package.name }}-cargo-${{ hashFiles('**/Cargo.lock') }}

            - name: Install dependencies
              if: ${{ matrix.package.dependencies }}
              run: sudo apt-get install ${{ matrix.package.dependencies }}

            - name: Build ${{ matrix.package.name }}
              working-directory: MoosicBoxServer
              run: |
                  cargo build \
                        --manifest-path=${{ matrix.package.path }}/Cargo.toml \
                        --verbose \
                        --features=fail-on-warnings${{ matrix.package.features && format(',{0}', matrix.package.features) || '' }}

            - name: Run ${{ matrix.package.name }} tests
              working-directory: MoosicBoxServer
              run: |
                  cargo test \
                        --manifest-path=${{ matrix.package.path }}/Cargo.toml \
                        --verbose \
                        --features=fail-on-warnings${{ matrix.package.features && format(',{0}', matrix.package.features) || '' }}
