name: Build and Test

on:
    push:
        branches: ['master']
    pull_request:
        branches: ['master']

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                package:
                    - name: core
                      path: packages/core

                    - name: files
                      path: packages/files

                    - name: menu
                      path: packages/menu

                    - name: ws
                      path: packages/ws

                    - name: server
                      path: server

        steps:
            - name: Checkout audiotags
              uses: actions/checkout@master
              with:
                  repository: BSteffaniak/audiotags
                  ref: feat/add-full-date-capabilities
                  path: audiotags

            - uses: actions/checkout@v3
              with:
                  path: MoosicBoxServer

            - name: ⚡ Cache cargo
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.cargo/registry
                      ~/.cargo/git
                      target
                  key: ${{ runner.os }}-${{ matrix.package.name }}-cargo-${{ hashFiles('**/Cargo.lock') }}

            - name: Build ${{ matrix.package.name }}
              working-directory: MoosicBoxServer
              run: |
                  cargo build \
                        --manifest-path=${{ matrix.package.path }}/Cargo.toml \
                        --verbose \
                        --features=fail-on-warnings

            - name: Run ${{ matrix.package.name }} tests
              working-directory: MoosicBoxServer
              run: |
                  cargo test \
                        --manifest-path=${{ matrix.package.path }}/Cargo.toml \
                        --verbose
