name: Build and Test

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ${{ matrix.package.os }}

        strategy:
            fail-fast: false

            matrix:
                package:
                    - name: auth
                      path: packages/auth
                      os: ubuntu-latest
                      cargo: --no-default-features

                    - name: auth-api
                      path: packages/auth
                      os: ubuntu-latest
                      cargo: --no-default-features
                      features: api

                    - name: converter
                      path: packages/converter
                      os: ubuntu-latest
                      cargo: --no-default-features

                    - name: converter-default
                      path: packages/converter
                      os: ubuntu-latest

                    - name: converter-aac
                      path: packages/converter
                      os: ubuntu-latest
                      cargo: --no-default-features
                      features: aac

                    - name: converter-mp3
                      path: packages/converter
                      os: ubuntu-latest
                      cargo: --no-default-features
                      features: mp3

                    - name: converter-opus
                      path: packages/converter
                      os: ubuntu-latest
                      cargo: --no-default-features
                      features: opus

                    - name: core
                      path: packages/core
                      os: ubuntu-latest

                    - name: env_utils
                      path: packages/env_utils
                      os: ubuntu-latest

                    - name: files
                      path: packages/files
                      os: ubuntu-latest

                    - name: image
                      path: packages/image
                      os: ubuntu-latest
                      cargo: --no-default-features
                      features: image

                    - name: image-libvips
                      path: packages/image
                      dependencies: sudo apt-get update && sudo apt-get install libvips-dev
                      os: ubuntu-latest

                    - name: image-windows
                      path: packages/image
                      os: windows-latest
                      cargo: --no-default-features
                      features: image

                    - name: menu
                      path: packages/menu
                      os: ubuntu-latest

                    - name: player
                      path: packages/player
                      os: ubuntu-latest
                      dependencies: sudo apt-get update && sudo apt-get install libasound2-dev
                      cargo: --no-default-features
                      features: cpal

                    - name: ws
                      path: packages/ws
                      os: ubuntu-latest

                    - name: tunnel_server
                      path: tunnel_server
                      os: ubuntu-latest
                      env: TUNNEL_ACCESS_TOKEN=123

                    - name: tunnel_server-base64
                      path: tunnel_server
                      os: ubuntu-latest
                      env: TUNNEL_ACCESS_TOKEN=123
                      features: base64

                    - name: tunnel_server-base
                      path: tunnel_server
                      os: ubuntu-latest
                      env: TUNNEL_ACCESS_TOKEN=123
                      cargo: --no-default-features

                    - name: server-static-token-auth
                      path: server
                      os: ubuntu-latest
                      dependencies: sudo apt-get update && sudo apt-get install libasound2-dev
                      cargo: --no-default-features
                      features: static-token-auth,cpal
                      env: STATIC_TOKEN=123

                    - name: server-cpal
                      path: server
                      os: ubuntu-latest
                      dependencies: sudo apt-get update && sudo apt-get install libasound2-dev
                      cargo: --no-default-features
                      features: cpal

                    - name: server-pulseaudio-standard
                      path: server
                      os: ubuntu-latest
                      dependencies: sudo apt-get update && sudo apt-get install pulseaudio
                      cargo: --no-default-features
                      features: pulseaudio-standard

                    - name: server-pulseaudio-simple
                      path: server
                      os: ubuntu-latest
                      dependencies: sudo apt-get update && sudo apt-get install pulseaudio
                      cargo: --no-default-features
                      features: pulseaudio-simple

                    - name: server-all
                      path: server
                      os: ubuntu-latest
                      dependencies: sudo apt-get update && sudo apt-get install libasound2-dev
                      cargo: --no-default-features
                      features: cpal

                    - name: stream_utils
                      path: packages/stream_utils
                      os: ubuntu-latest

                    - name: symphonia_player-cpal-windows
                      path: players/symphonia_player
                      os: windows-latest
                      cargo: --no-default-features
                      features: cpal

                    - name: symphonia_player-all-windows
                      path: players/symphonia_player
                      os: windows-latest

                    - name: symphonia_player-cpal-ubuntu
                      path: players/symphonia_player
                      os: ubuntu-latest
                      dependencies: sudo apt-get update && sudo apt-get install libasound2-dev
                      cargo: --no-default-features
                      features: cpal

                    - name: symphonia_player-pulseaudio-standard-ubuntu
                      path: players/symphonia_player
                      os: ubuntu-latest
                      dependencies: sudo apt-get update && sudo apt-get install pulseaudio
                      cargo: --no-default-features
                      features: pulseaudio-standard

                    - name: symphonia_player-pulseaudio-simple-ubuntu
                      path: players/symphonia_player
                      os: ubuntu-latest
                      dependencies: sudo apt-get update && sudo apt-get install pulseaudio
                      cargo: --no-default-features
                      features: pulseaudio-simple

                    - name: symphonia_player-all-ubuntu
                      path: players/symphonia_player
                      os: ubuntu-latest
                      dependencies: sudo apt-get update && sudo apt-get install pulseaudio libasound2-dev

                    - name: symphonia_player-cpal-macos
                      path: players/symphonia_player
                      os: macos-latest
                      cargo: --no-default-features
                      features: cpal

                    - name: symphonia_player-pulseaudio-standard-macos
                      path: players/symphonia_player
                      os: macos-latest
                      dependencies: brew install pulseaudio
                      cargo: --no-default-features
                      features: pulseaudio-standard

                    - name: symphonia_player-pulseaudio-simple-macos
                      path: players/symphonia_player
                      os: macos-latest
                      dependencies: brew install pulseaudio
                      cargo: --no-default-features
                      features: pulseaudio-simple

                    - name: symphonia_player-all-macos
                      path: players/symphonia_player
                      os: macos-latest
                      dependencies: brew install pulseaudio

        steps:
            - name: Checkout audiotags
              uses: actions/checkout@master
              with:
                  repository: BSteffaniak/audiotags
                  ref: feat/add-full-date-capabilities
                  path: audiotags

            - uses: actions/checkout@v3
              with:
                  path: MoosicBoxServer

            - name: ⚡ Cache cargo
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.cargo/registry
                      ~/.cargo/git
                      target
                  key: ${{ runner.os }}-${{ matrix.package.name }}-cargo-${{ hashFiles('**/Cargo.lock') }}

            - name: Install dependencies
              if: ${{ matrix.package.dependencies }}
              run: ${{ matrix.package.dependencies }}

            - name: Build ${{ matrix.package.name }}
              shell: bash
              working-directory: MoosicBoxServer
              run: |
                  ${{ matrix.package.env }} cargo build \
                        --manifest-path=${{ matrix.package.path }}/Cargo.toml \
                        --verbose \
                        --features=fail-on-warnings${{ matrix.package.features && format(',{0}', matrix.package.features) || '' }} ${{ matrix.package.cargo }}

            - name: Run ${{ matrix.package.name }} tests
              shell: bash
              working-directory: MoosicBoxServer
              run: |
                  ${{ matrix.package.env }} cargo test \
                        --manifest-path=${{ matrix.package.path }}/Cargo.toml \
                        --verbose \
                        --features=fail-on-warnings${{ matrix.package.features && format(',{0}', matrix.package.features) || '' }} ${{ matrix.package.cargo }}
