name: Build and Test

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ${{ matrix.package.os }}

        strategy:
            fail-fast: false

            matrix:
                package:
                    - name: auth
                      path: packages/auth
                      os: ubuntu-latest
                      cargo: --no-default-features

                    - name: auth-api
                      path: packages/auth
                      os: ubuntu-latest
                      cargo: --no-default-features
                      features: api

                    - name: converter
                      path: packages/converter
                      os: ubuntu-latest
                      cargo: --no-default-features

                    - name: converter-default
                      path: packages/converter
                      os: ubuntu-latest

                    - name: converter-aac
                      path: packages/converter
                      os: ubuntu-latest
                      cargo: --no-default-features
                      features: aac

                    - name: converter-mp3
                      path: packages/converter
                      os: ubuntu-latest
                      cargo: --no-default-features
                      features: mp3

                    - name: converter-opus
                      path: packages/converter
                      os: ubuntu-latest
                      cargo: --no-default-features
                      features: opus

                    - name: config
                      path: packages/config
                      os: ubuntu-latest

                    - name: core
                      path: packages/core
                      os: ubuntu-latest

                    - name: database
                      path: packages/database
                      os: ubuntu-latest

                    - name: downloader
                      path: packages/downloader
                      os: ubuntu-latest

                    - name: downloader-no-default-features
                      path: packages/downloader
                      os: ubuntu-latest
                      cargo: --no-default-features

                    - name: downloader-api
                      path: packages/downloader
                      os: ubuntu-latest
                      cargo: --no-default-features
                      features: api

                    - name: env_utils
                      path: packages/env_utils
                      os: ubuntu-latest

                    - name: files
                      path: packages/files
                      os: ubuntu-latest

                    - name: image
                      path: packages/image
                      os: ubuntu-latest
                      cargo: --no-default-features
                      features: image

                    - name: image-libvips
                      path: packages/image
                      dependencies: sudo apt-get update && sudo apt-get install libvips-dev
                      os: ubuntu-latest

                    - name: image-windows
                      path: packages/image
                      os: windows-latest
                      cargo: --no-default-features
                      features: image

                    - name: json_utils
                      path: packages/json_utils
                      os: ubuntu-latest

                    - name: menu
                      path: packages/menu
                      os: ubuntu-latest

                    - name: music_api
                      path: packages/music_api
                      os: ubuntu-latest

                    - name: paging
                      path: packages/paging
                      os: ubuntu-latest

                    - name: player
                      path: packages/player
                      os: ubuntu-latest
                      dependencies: sudo apt-get update && sudo apt-get install libasound2-dev
                      cargo: --no-default-features
                      features: cpal

                    - name: qobuz
                      path: packages/qobuz
                      os: ubuntu-latest

                    - name: qobuz-no-default-features
                      path: packages/qobuz
                      os: ubuntu-latest
                      cargo: --no-default-features

                    - name: qobuz-api
                      path: packages/qobuz
                      os: ubuntu-latest
                      cargo: --no-default-features
                      features: api

                    - name: qobuz-db
                      path: packages/qobuz
                      os: ubuntu-latest
                      cargo: --no-default-features
                      features: db

                    - name: search
                      path: packages/search
                      os: ubuntu-latest

                    - name: search-no-default-features
                      path: packages/search
                      os: ubuntu-latest
                      cargo: --no-default-features

                    - name: search-api
                      path: packages/search
                      os: ubuntu-latest
                      cargo: --no-default-features
                      features: api

                    - name: search-db
                      path: packages/search
                      os: ubuntu-latest
                      cargo: --no-default-features
                      features: db

                    - name: ws
                      path: packages/ws
                      os: ubuntu-latest

                    - name: tunnel
                      path: packages/tunnel
                      os: ubuntu-latest

                    - name: tunnel-base64
                      path: packages/tunnel
                      os: ubuntu-latest
                      features: base64

                    - name: tunnel-base
                      path: packages/tunnel
                      os: ubuntu-latest
                      cargo: --no-default-features

                    - name: tunnel_sender
                      path: packages/tunnel_sender
                      os: ubuntu-latest

                    - name: tunnel_sender-base64
                      path: packages/tunnel_sender
                      os: ubuntu-latest
                      features: base64

                    - name: tunnel_sender-base
                      path: packages/tunnel_sender
                      os: ubuntu-latest
                      cargo: --no-default-features

                    - name: tunnel_server
                      path: packages/tunnel_server
                      os: ubuntu-latest
                      env: TUNNEL_ACCESS_TOKEN=123

                    - name: tunnel_server-base64
                      path: packages/tunnel_server
                      os: ubuntu-latest
                      env: TUNNEL_ACCESS_TOKEN=123
                      features: base64

                    - name: tunnel_server-base
                      path: packages/tunnel_server
                      os: ubuntu-latest
                      env: TUNNEL_ACCESS_TOKEN=123
                      cargo: --no-default-features

                    - name: server-static-token-auth
                      path: packages/server
                      os: ubuntu-latest
                      dependencies: sudo apt-get update && sudo apt-get install libasound2-dev
                      cargo: --no-default-features
                      features: static-token-auth,cpal
                      env: STATIC_TOKEN=123

                    - name: server-cpal
                      path: packages/server
                      os: ubuntu-latest
                      dependencies: sudo apt-get update && sudo apt-get install libasound2-dev
                      cargo: --no-default-features
                      features: cpal

                    - name: server-pulseaudio-standard
                      path: packages/server
                      os: ubuntu-latest
                      dependencies: sudo apt-get update && sudo apt-get install pulseaudio
                      cargo: --no-default-features
                      features: pulseaudio-standard

                    - name: server-pulseaudio-simple
                      path: packages/server
                      os: ubuntu-latest
                      dependencies: sudo apt-get update && sudo apt-get install pulseaudio
                      cargo: --no-default-features
                      features: pulseaudio-simple

                    - name: server-all
                      path: packages/server
                      os: ubuntu-latest
                      dependencies: sudo apt-get update && sudo apt-get install libasound2-dev
                      cargo: --no-default-features
                      features: cpal

                    - name: server-no-default-features
                      path: packages/server
                      os: ubuntu-latest
                      cargo: --no-default-features

                    - name: server-aac
                      path: packages/server
                      os: ubuntu-latest
                      cargo: --no-default-features
                      features: aac

                    - name: server-flac
                      path: packages/server
                      os: ubuntu-latest
                      cargo: --no-default-features
                      features: flac

                    - name: server-mp3
                      path: packages/server
                      os: ubuntu-latest
                      cargo: --no-default-features
                      features: mp3

                    - name: server-opus
                      path: packages/server
                      os: ubuntu-latest
                      cargo: --no-default-features
                      features: opus

                    - name: scan
                      path: packages/scan
                      os: ubuntu-latest

                    - name: scan-no-default-features
                      path: packages/scan
                      os: ubuntu-latest
                      cargo: --no-default-features

                    - name: scan-local
                      path: packages/scan
                      os: ubuntu-latest
                      cargo: --no-default-features
                      features: local

                    - name: scan-tidal
                      path: packages/scan
                      os: ubuntu-latest
                      cargo: --no-default-features
                      features: tidal

                    - name: tidal
                      path: packages/tidal
                      os: ubuntu-latest

                    - name: tidal-no-default-features
                      path: packages/tidal
                      os: ubuntu-latest
                      cargo: --no-default-features

                    - name: tidal-api
                      path: packages/tidal
                      os: ubuntu-latest
                      cargo: --no-default-features
                      features: api

                    - name: tidal-db
                      path: packages/tidal
                      os: ubuntu-latest
                      cargo: --no-default-features
                      features: db

                    - name: stream_utils
                      path: packages/stream_utils
                      os: ubuntu-latest

                    - name: symphonia_player-cpal-windows
                      path: packages/symphonia_player
                      os: windows-latest
                      cargo: --no-default-features
                      features: cpal

                    - name: symphonia_player-all-windows
                      path: packages/symphonia_player
                      os: windows-latest

                    - name: symphonia_player-cpal-ubuntu
                      path: packages/symphonia_player
                      os: ubuntu-latest
                      dependencies: sudo apt-get update && sudo apt-get install libasound2-dev
                      cargo: --no-default-features
                      features: cpal

                    - name: symphonia_player-pulseaudio-standard-ubuntu
                      path: packages/symphonia_player
                      os: ubuntu-latest
                      dependencies: sudo apt-get update && sudo apt-get install pulseaudio
                      cargo: --no-default-features
                      features: pulseaudio-standard

                    - name: symphonia_player-pulseaudio-simple-ubuntu
                      path: packages/symphonia_player
                      os: ubuntu-latest
                      dependencies: sudo apt-get update && sudo apt-get install pulseaudio
                      cargo: --no-default-features
                      features: pulseaudio-simple

                    - name: symphonia_player-all-ubuntu
                      path: packages/symphonia_player
                      os: ubuntu-latest
                      dependencies: sudo apt-get update && sudo apt-get install pulseaudio libasound2-dev

                    - name: symphonia_player-cpal-macos
                      path: packages/symphonia_player
                      os: macos-latest
                      cargo: --no-default-features
                      features: cpal

                    - name: symphonia_player-pulseaudio-standard-macos
                      path: packages/symphonia_player
                      os: macos-latest
                      dependencies: brew install pulseaudio
                      cargo: --no-default-features
                      features: pulseaudio-standard

                    - name: symphonia_player-pulseaudio-simple-macos
                      path: packages/symphonia_player
                      os: macos-latest
                      dependencies: brew install pulseaudio
                      cargo: --no-default-features
                      features: pulseaudio-simple

                    # - name: symphonia_player-all-macos
                    #   path: packages/symphonia_player
                    #   os: macos-latest
                    #   dependencies: brew install pulseaudio

        steps:
            - uses: actions/checkout@v4
              with:
                  path: MoosicBoxServer

            - name: ⚡ Cache cargo
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.cargo/registry
                      ~/.cargo/git
                      target
                  key: ${{ runner.os }}-${{ matrix.package.name }}-cargo-${{ hashFiles('**/Cargo.lock') }}

            - name: Install dependencies
              if: ${{ matrix.package.dependencies }}
              run: ${{ matrix.package.dependencies }}

            - name: Build ${{ matrix.package.name }}
              shell: bash
              working-directory: MoosicBoxServer
              run: |
                  ${{ matrix.package.env }} cargo build \
                        --manifest-path=${{ matrix.package.path }}/Cargo.toml \
                        --verbose \
                        --features=fail-on-warnings${{ matrix.package.features && format(',{0}', matrix.package.features) || '' }} ${{ matrix.package.cargo }}

            - name: Run ${{ matrix.package.name }} tests
              shell: bash
              working-directory: MoosicBoxServer
              run: |
                  ${{ matrix.package.env }} cargo test \
                        --manifest-path=${{ matrix.package.path }}/Cargo.toml \
                        --verbose \
                        --features=fail-on-warnings${{ matrix.package.features && format(',{0}', matrix.package.features) || '' }} ${{ matrix.package.cargo }}
