name: Deploy TunnelServer

on: workflow_dispatch

env:
    CARGO_TERM_COLOR: always
    AWS_REGION: us-east-1

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: dtolnay/rust-toolchain@stable

            - name: Install doctl
              uses: digitalocean/action-doctl@v2
              with:
                  token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

            - name: Save DigitalOcean kubeconfig
              run: doctl kubernetes cluster kubeconfig save moosicbox-tunnel-prod

            - name: Deploy
              shell: bash
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  TUNNEL_ACCESS_TOKEN: ${{ secrets.TUNNEL_ACCESS_TOKEN }}
              run: |
                  ./do-deploy.sh moosicbox-tunnel-server
