name: Deploy LoadBalancer

on:
    workflow_dispatch:
        inputs:
            stage:
                description: 'Stage'
                required: false
                default: 'prod'
            force:
                description: 'K8S Patch Force'
                required: false
                default: 'false'

env:
    CARGO_TERM_COLOR: always

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: dtolnay/rust-toolchain@stable

            - uses: pnpm/action-setup@v3
              name: Install pnpm
              with:
                  version: 9
                  run_install: false

            - name: Deploy
              shell: bash
              env:
                  DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_REGION: us-east-1
                  PULUMI_K8S_ENABLE_PATCH_FORCE: ${{ github.event.inputs.force }}
              run: |
                  pnpm install
                  pnpm sst install
                  pnpm sst deploy --stage ${{ github.event.inputs.stage }}
