name: Deploy LoadBalancer

on:
    workflow_dispatch:
        inputs:
            extra_clusters:
                description: "Extra Clusters"
                required: false
                default: ""

env:
    CARGO_TERM_COLOR: always
    AWS_REGION: us-east-1

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: dtolnay/rust-toolchain@stable

            - name: Install doctl
              uses: digitalocean/action-doctl@v2
              with:
                  token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

            - name: Save DigitalOcean kubeconfig
              run: doctl kubernetes cluster kubeconfig save moosicbox-prod

            - name: Deploy
              shell: bash
              env:
                  CLUSTERS: "tunnel.moosicbox.com:moosicbox-tunnel-service:8004;cloud.moosicbox.com:moosicbox-service:8010;${{ github.event.inputs.extra_clusters }}"
              run: |
                  ./do-deploy.sh moosicbox-tunnel-server-lb kubernetes/tunnel-server
