name: Marketing Website Auto-upgrade Node Dependencies

on:
    workflow_dispatch:
    schedule:
        - cron: '20 4 * * *'

env:
    CARGO_TERM_COLOR: always
    AWS_REGION: us-east-1

jobs:
    upgrade:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  token: ${{ secrets.MOOSICBOX_BOT_UPGRADES_TOKEN }}

            - uses: pnpm/action-setup@v3
              name: Install pnpm
              with:
                  version: 9
                  run_install: false

            - name: Get pnpm store directory
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

            - name: ⚡ Cache pnpm
              uses: actions/cache@v4
              with:
                  path: ${{ env.STORE_PATH }}
                  key: ${{ matrix.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ matrix.os }}-pnpm-store-

            - name: pnpm install
              working-directory: marketing-website
              run: |
                  pnpm install
                  pnpm sst install

            - name: Upgrade
              id: upgrade
              working-directory: marketing-website
              shell: bash
              run: |
                  pnpm update
                  if [ -n "$(git status --porcelain)" ]; then
                      echo "Found upgrades"
                      echo "upgraded=true" >> "$GITHUB_OUTPUT"
                      pnpm sst install
                  else
                      echo "No upgrades"
                      echo "upgraded=false" >> "$GITHUB_OUTPUT"
                  fi

            - name: Validate
              if: ${{ steps.upgrade.outputs.upgraded == 'true' }}
              working-directory: marketing-website
              shell: bash
              run: pnpm validate

            - name: Commit
              if: ${{ steps.upgrade.outputs.upgraded == 'true' }}
              shell: bash
              run: |
                  git config user.name "MoosicBoxBot"
                  git config user.email "MoosicBoxBot@gmail.com"
                  git add .
                  git commit --message "Upgrade marketing-website node dependencies"
                  echo "Pushing upgrades"
                  git push origin master
