name: Marketing Website Rust Build and Validate

on:
    push:
        branches: ['master']
        paths:
            - packages/marketing_site/**
            - .github/workflows/marketing-website-rust-build-and-test.yml
    pull_request:
        branches: ['master']
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false

        steps:
            - uses: actions/checkout@v4

            - uses: pnpm/action-setup@v3
              name: Install pnpm
              with:
                  version: 9
                  run_install: false

            - name: Get pnpm store directory
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

            - name: pnpm install
              working-directory: packages/marketing_site
              run: |
                  pnpm install

            - name: sst install
              working-directory: packages/marketing_site
              run: |
                  pnpm sst install

            - name: pretty
              working-directory: packages/marketing_site
              run: pnpm pretty

            - name: lint
              working-directory: packages/marketing_site
              run: pnpm lint

            - name: typecheck
              working-directory: packages/marketing_site
              run: pnpm typecheck
