name: Publish Crates

on:
    workflow_dispatch:
    schedule:
        - cron: '*/30 * * * *'

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: dtolnay/rust-toolchain@stable

            - name: Install cargo-workspaces
              shell: bash
              run: cargo install cargo-workspaces

            - name: Deploy
              shell: bash
              env:
                  STATIC_TOKEN: 123
                  TUNNEL_ACCESS_TOKEN: 123
                  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
              run: |
                  cargo workspaces publish --publish-as-is
