name: Tauri Build and Test

on:
    push:
        branches: ['master']
        paths:
            - packages/**
            - '*.toml'
            - Cargo.lock
            - .github/workflows/tauri-build-and-test.yml
    pull_request:
        branches: ['master']

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]

        steps:
            - name: Checkout audiotags
              uses: actions/checkout@v4
              with:
                  repository: BSteffaniak/audiotags
                  ref: feat/add-full-date-capabilities
                  path: audiotags

            - uses: actions/checkout@v4
              with:
                  path: MoosicBox

            - uses: dtolnay/rust-toolchain@stable

            - name: ⚡ Cache cargo
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.cargo/registry
                      ~/.cargo/git
                      target
                  key: ${{ matrix.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

            - name: Install Dependencies
              if: ${{ matrix.os == 'ubuntu-latest' }}
              run: |
                  sudo apt update
                  sudo apt install libwebkit2gtk-4.1-dev \
                      build-essential \
                      curl \
                      wget \
                      file \
                      libssl-dev \
                      libgtk-3-dev \
                      libayatana-appindicator3-dev \
                      librsvg2-dev \
                      libasound2-dev \
                      libsoup-3.0-dev

            - name: Build
              working-directory: MoosicBox/packages/app/tauri/src-tauri
              env:
                  APTABASE_APP_KEY: ${{ secrets.APTABASE_APP_KEY }}
              run: cargo build --verbose

            - name: Run tests
              working-directory: MoosicBox/packages/app/tauri/src-tauri
              env:
                  APTABASE_APP_KEY: ${{ secrets.APTABASE_APP_KEY }}
              run: cargo test --verbose

            - name: Copy Files
              working-directory: MoosicBox/packages/app/tauri
              shell: bash
              run: |
                  ./copy-files.sh

            - uses: pnpm/action-setup@v3
              name: Install pnpm
              with:
                  version: 9
                  run_install: false

            - name: Get pnpm store directory
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

            - name: ⚡ Cache pnpm
              uses: actions/cache@v4
              with:
                  path: ${{ env.STORE_PATH }}
                  key: ${{ matrix.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ matrix.os }}-pnpm-store-

            - name: Generate config
              working-directory: MoosicBox/packages/app/tauri
              run: cargo run --package moosicbox_app_create_config -- -o src/config.ts

            - name: pnpm install
              working-directory: MoosicBox/packages/app/tauri
              run: pnpm install

            - name: Build Tauri App
              working-directory: MoosicBox/packages/app/tauri
              env:
                  APTABASE_APP_KEY: ${{ secrets.APTABASE_APP_KEY }}
              run: pnpm tauri build

            - uses: dtolnay/rust-toolchain@nightly

            - name: Install cargo-machete
              shell: bash
              working-directory: MoosicBox/packages/app/tauri
              run: |
                  cargo install cargo-machete

            - name: Validate ${{ matrix.package.name }} dependencies (machete)
              shell: bash
              working-directory: MoosicBox/packages/app/tauri
              run: |
                  cargo machete --with-metadata
