[package]
authors     = ["Braden Steffaniak"]
categories  = ["database"]
description = "MoosicBox search package"
edition     = "2021"
keywords    = ["api", "database", "search", "tantivy"]
license     = "MPL-2.0"
name        = "moosicbox_search"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBoxServer"
version     = "0.1.0"

[dependencies]
moosicbox_assert = { path = "../assert", default-features = false }
moosicbox_config = { path = "../config" }
moosicbox_core = { path = "../core", default-features = false, features = [
    "tantivy",
] }
moosicbox_database = { path = "../database", default-features = false, features = [
    "sqlite-sqlx",
] }
moosicbox_json_utils = { path = "../json_utils", default-features = false, features = [
    "tantivy",
] }
moosicbox_task = { path = "../task" }

# API Dependencies
actix-web = { workspace = true, optional = true }
utoipa    = { workspace = true, optional = true }

itertools  = { workspace = true }
log        = { workspace = true }
regex      = { workspace = true }
serde      = { workspace = true }
serde_json = { workspace = true }
tantivy    = { workspace = true }
thiserror  = { workspace = true }
tokio      = { workspace = true }

[dev-dependencies]
moosicbox_config = { path = "../config", features = ["test"] }

pretty_assertions = { workspace = true }
serial_test       = { workspace = true }
static_init       = { workspace = true }
test-log          = { workspace = true }

[features]
default = ["api", "db", "openapi"]

fail-on-warnings = []

api     = ["db", "dep:actix-web"]
db      = []
openapi = ["dep:utoipa"]
