[package]
authors = ["Braden Steffaniak"]
edition = "2021"
name    = "moosicbox_search"
version = "0.1.0"

[dependencies]
moosicbox_config = { path = "../config" }
moosicbox_json_utils = { path = "../json_utils", default-features = false, features = [
    "tantivy",
] }

# API Dependencies
actix-web  = { workspace = true, optional = true }
serde      = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }

# DB Dependencies
moosicbox_core = { path = "../core", optional = true, default-features = false }

itertools = { workspace = true }
log       = { workspace = true }
once_cell = { workspace = true }
regex     = { workspace = true }
tantivy   = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
moosicbox_config = { path = "../config", features = ["test"] }

pretty_assertions = { workspace = true }
serial_test       = { workspace = true }
static_init       = { workspace = true }
test-log          = { workspace = true }

[features]
default = ["api", "db"]

fail-on-warnings = []

api = ["db", "dep:actix-web", "dep:serde", "dep:serde_json"]
db  = ["dep:moosicbox_core"]
